JOEY_DECKS = {
    "Amateur": [
        ("Anthrosaurus", 1),
        ("Claw Reacher", 1),
        ("Destroyer Golem", 1),
        ("Kagemusha of the Blue Flame", 1),
        ("Kageningen", 1),
        ("Meotoko", 1),
        ("M-Warrior #1", 1),
        ("M-Warrior #2", 1),
        ("Rock Ogre Grotto #1", 1),
        ("Skull Stalker", 1),
        ("Stone Armadiller", 1),
        ("The Furious Sea King", 1),
    ],
    "Manga - Duelist Kingdom": [
        ("Armored Lizard", 1),
        ("Axe Raider", 1),
        ("Baby Dragon", 1),
        ("Battle Steer", 1),
        ("Kojikocy", 1),
        ("Flame Swordsman", 1),
        ("Garoozis", 1),
        ("Giltia the D. Knight", 1),
        ("Glassman [M]", 1),
        ("Karbonala Warrior", 1),
        ("Battle Warrior", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Rock Ogre Grotto #1", 1),
        ("Swamp Battleguard", 1),
        ("Tiger Axe", 1),
        ("Wolf", 1),
        ("Red-Eyes Black Metal Dragon", 1),
        ("Thousand Dragon", 1),
        ("Black Skull Dragon", 1),
        ("Copycat", 1),
        ("Dragon Nails", 1),
        ("Salamandra", 1),
        ("Shield & Sword", 1),
        ("Time Wizard", 1),
        ("Whirlpool [M]", 1),
        ("Trap Hole of Spikes", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
    ],
    "Duelist Kingdom": [
        ("Anthrosaurus", 1),
        ("Armored Lizard", 1),
        ("Axe Raider", 1),
        ("Baby Dragon", 1),
        ("Battle Steer", 1),
        ("Battle Warrior", 1),
        ("Claw Reacher", 1),
        ("Destroyer Golem", 1),
        ("Flame Swordsman", 1),
        ("Garoozis", 1),
        ("Giltia the D. Knight", 1),
        ("Glass Man [A]", 1),
        ("Kagemusha of the Blue Flame", 1),
        ("Kageningen", 1),
        ("Kojikocy", 1),
        ("Leogun", 1),
        ("M-Warrior #1", 1),
        ("M-Warrior #2", 1),
        ("Masaki the Legendary Swordsman", 1),
        ("Meotoko", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Rock Ogre Grotto #1", 1),
        ("Rude Kaiser", 1),
        ("Skull Stalker", 1),
        ("Stone Armadiller", 1),
        ("Tiger Axe", 1),
        ("The Furious Sea King", 1),
        ("Kuriboh", 1),
        ("Lava Battleguard", 1),
        ("Swamp Battleguard", 1),
        ("Red-Eyes Black Metal Dragon", 1),
        ("Thousand Dragon", 1),
        ("Black Skull Dragon", 1),
        ("Copycat", 1),
        ("Dragon Nails", 1),
        ("Salamandra", 1),
        ("Shield & Sword", 1),
        ("Time Wizard", 1),
        ("Trap Hole of Spikes", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
        ("Trap Hole", 1),
    ],
    "Joey vs. Duke Devlin": [
        ("Goblin Attack Force", 1),
        ("Mad Sword Beast", 1),
        ("Sword Hunter", 1),
    ],
    "Manga - Battle City": [
        ("Alligator's Sword", 1),
        ("Baby Dragon", 1),
        ("Fortress Whale", 1),
        ("Giltia the D. Knight", 1),
        ("Little-Winguard", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Swordsman of Landstar", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Insect Queen", 1),
        ("Jinzo", 1),
        ("Panther Warrior", 1),
        ("Parasite Paracide", 1),
        ("Rocket Warrior", 1),
        ("The Legendary Fisherman", 1),
        ("Thousand Dragon", 1),
        ("Alligator's Sword Dragon", 1),
        ("Fairy Box", 1),
        ("Foolish Burial", 1),
        ("Giant Trunade", 1),
        ("Graceful Dice", 1),
        ("Lightning Blade", 1),
        ("Polymerization", 1),
        ("Question", 1),
        ("Roulette Spider", 1),
        ("Scapegoat", 1),
        ("Shield & Sword", 1),
        ("Time Wizard", 1),
        ("Trap Hole of Spikes", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
        ("Magical Arm Shield", 1),
        ("Skull Dice", 1),
    ],
    "Battle City": [
        ("Alligator's Sword", 1),
        ("Axe Raider", 1),
        ("Baby Dragon", 1),
        ("Battle Warrior", 1),
        ("Flame Swordsman", 1),
        ("Garoozis", 1),
        ("Giltia the D. Knight", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Swordsman of Landstar", 1),
        ("Little-Winguard", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Hayabusa Knight", 1),
        ("Insect Queen", 1),
        ("Jinzo", 1),
        ("Panther Warrior", 1),
        ("Parasite Paracide", 1),
        ("Rocket Warrior", 1),
        ("The Legendary Fisherman", 1),
        ("Thousand Dragon", 1),
        ("Alligator's Sword Dragon", 1),
        ("Energy Drain", 1),
        ("Fairy Box", 1),
        ("Foolish Burial", 1),
        ("Giant Trunade", 1),
        ("Graceful Dice", 1),
        ("Legendary Sword", 1),
        ("Lightning Blade", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Question", 1),
        ("Roulette Spider", 1),
        ("Salamandra", 1),
        ("Scapegoat", 1),
        ("Shield & Sword", 1),
        ("Skull Dice", 1),
        ("Time Wizard", 1),
        ("Trap Hole of Spikes", 1),
        ("Collected Power", 1),
        ("Gamble", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
        ("Magical Arm Shield", 1),
        ("Nutrient Z", 1),
    ],
    "Possessed": [
        ("Alligator's Sword", 1),
        ("Gearfried the Iron Knight", 1),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 1),
        ("Attrition [A]", 1),
        ("Graceful Dice", 1),
        ("Hinotama", 3),
        ("Meteor of Destruction", 1),
        ("Raigeki", 1),
        ("Skull Dice", 1),
        ("Magical Arm Shield", 1),
    ],
    "Flashback": [
        ("Axe Raider", 1),
        ("Battle Warrior", 1),
        ("Flame Swordsman", 1),
        ("Hero of the East", 1),
        ("M-Warrior #1", 1),
        ("M-Warrior #2", 1),
        ("Tiger Axe", 1),
        ("Panther Warrior", 1),
        ("Gust Fan", 1),
        ("Legendary Sword", 1),
        ("Shield & Sword", 1),
    ],
    "Virtual World": [
        ("Alligator's Sword", 1),
        ("Axe Raider", 1),
        ("Baby Dragon", 1),
        ("Battle Warrior", 1),
        ("Flame Swordsman", 1),
        ("Swordsman of Landstar", 1),
        ("Little-Winguard", 1),
        ("Cyber Harpie Lady", 1),
        ("Gearfried the Iron Knight", 1),
        ("Goblin Attack Force", 1),
        ("Hayabusa Knight", 1),
        ("Insect Queen", 1),
        ("Jinzo", 1),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 1),
        ("Sword Hunter", 1),
        ("Arduous Decision [A]", 1),
        ("Block Attack", 1),
        ("Burning Soul Sword [A]", 1),
        ("Double Snare", 1),
        ("Fairy Box", 1),
        ("Graceful Dice", 1),
        ("Harpie's Feather Duster", 1),
        ("Knight's Title", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Scapegoat", 1),
        ("Shield & Sword", 1),
        ("Skull Dice", 1),
        ("Bottomless Trap Hole", 1),
        ("Drop Off", 1),
        ("Gamble", 1),
        ("Kunai with Chain", 1),
        ("Silver Dollar [A]", 1),
    ],
    "Waking the Dragons": [
        ("Alligator's Sword", 1),
        ("Battle Warrior", 1),
        ("Brigadier of Landstar [A]", 1),
        ("Cyber-Tech Alligator", 1),
        ("Flame Swordsman", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Swordsman of Landstar", 1),
        ("Blue Flame Swordsman", 1),
        ("Fiber Jar", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gearfried the Swordmaster", 1),
        ("Gilford the Lightning", 1),
        ("Jinzo", 1),
        ("Marauding Captain", 1),
        ("Neko Mane King", 1),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 1),
        ("The Fiend Megacyber", 1),
        ("Time Wizard", 1),
        ("Paladin of Dark Dragon", 1),
        ("Lord of the Red", 1),
        ("Dark Dragon Ritual", 1),
        ("Monster Reborn", 1),
        ("Pot of Greed", 1),
        ("Red-Eyes Transmigration", 1),
        ("Release Restraint", 1),
        ("Roll of Fate [A]", 1),
        ("Scapegoat", 1),
        ("Skull Dice", 1),
        ("Star Blaster", 1),
        ("The Warrior Returning Alive", 1),
        ("The Claw of Hermos", 1),
        ("Big Bang Dragon Blow [A]", 1),
        ("Red-Eyes Black Dragon Sword", 1),
        ("Rocket Hermos Cannon", 1),
        ("Time Magic Hammer", 1),
        ("Aura Armor [A]", 1),
        ("Celebration of Creation [A]", 1),
        ("Compensation Mediation [A]", 1),
        ("Double Magical Arm Bind", 1),
        ("Drop Off", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
        ("Magical Arm Shield", 1),
        ("Metalmorph", 1),
        ("Take One Chance [A]", 1),
        ("Vow of Tribe [A]", 1),
    ],
    "Grand Championship": [
        ("Alligator's Sword", 1),
        ("Brigadier of Landstar [A]", 1),
        ("Grappler of Landstar [A]", 1),
        ("Knight of Landstar [A]", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Swordsman of Landstar", 1),
        ("Blue Flame Swordsman", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Goblin Attack Force", 1),
        ("Jinzo", 1),
        ("Maximum Six", 1),
        ("Panther Warrior", 1),
        ("Sasuke Samurai", 1),
        ("Little-Winguard", 1),
        ("Paladin of Dark Dragon", 1),
        ("Dangerous Machine Type-6", 1),
        ("Giant Trunade", 1),
        ("Graceful Dice", 1),
        ("Hyper Refresh [A]", 1),
        ("Landstar Forces [A]", 1),
        ("Landstar Shot [A]", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Release Restraint", 1),
        ("Roll of Fate [A]", 1),
        ("Scapegoat", 1),
        ("Skull Dice", 1),
        ("Star Blaster [A]", 1),
        ("Compensation Mediation [A]", 1),
        ("Silver Dollar [A]", 1),
    ],
    "Dawn of the Duel": [
        ("Flame Swordsman", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Gearfried the Iron Knight", 1),
    ],
    "Yu-Gi-Oh! R": [
        ("Alligator's Sword", 1),
        ("Divine Knight Ishzark", 1),
        ("Giltia the D. Knight", 1),
        ("Little-Winguard", 1),
        ("Swordsman of Landstar", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Jinzo", 1),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 1),
        ("The Legendary Fisherman", 1),
        ("Gilti-Gearfried the Magical Steel Knight", 1),
        ("Cross Shift [M]", 1),
        ("Extra Boost [M]", 1),
        ("Fairy Box", 1),
        ("Giant Trunade", 1),
        ("Polymerization", 1),
        ("Roulette Spider", 1),
        ("Scapegoat", 1),
        ("Shield & Sword", 1),
        ("Skull Dice", 1),
        ("Stop Defense", 1),
        ("Summon Capture [M]", 1),
        ("Take Over [M]", 1),
        ("Time Wizard", 1),
        ("Trap Hole of Spikes", 1),
        ("Dramatic Rescue", 1),
        ("Graverobber", 1),
        ("Magical Arm Shield", 1),
        ("Probability Change [M]", 1),
        ("Relentless Attacks [M]", 1),
        ("Time Machine", 1),
    ],
    "Pyramid of Light": [
        ("Baby Dragon", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Rocket Warrior", 1),
        ("Little-Winguard", 1),
    ],
    "Championship Series Providence 2012": [
        ("Alligator's Sword", 1),
        ("Axe Raider", 1),
        ("Baby Dragon", 1),
        ("Goblin Attack Force", 1),
        ("Alligator's Sword Dragon", 1),
        ("Giant Trunade", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Scapegoat", 1),
        ("Nutrient Z", 1),
        ("Kunai with Chain", 1),
    ],
    "North American World Championship Qualifiers 2012": [
        ("Alligator's Sword", 1),
        ("Axe Raider", 1),
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Tiger Axe", 1),
        ("Copycat", 1),
        ("Gearfried the Iron Knight", 1),
        ("Little-Winguard", 1),
        ("Jinzo", 1),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 1),
        ("Time Wizard", 1),
        ("Alligator's Sword Dragon", 1),
        ("Scapegoat", 1),
        ("Silent Doom", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Drop Off", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
        ("Magical Arm Shield", 1),
        ("Nutrient Z", 1),
        ("Psychic Shockwave", 1),
        ("Trap Hole", 1),
        ("Skull Dice", 1),
    ],
    "YCS Origins 2016 Special": [
        ("Red-Eyes Black Dragon", 1),
        ("Beast of Talwar", 1),
        ("Flame Manipulator", 1),
        ("Masaki the Legendary Swordsman", 1),
        ("Baby Dragon", 1),
        ("Black Metal Dragon", 2),
        ("The Black Stone of Legend", 1),
        ("Red-Eyes Retro Dragon", 1),
        ("Thousand Dragon", 1),
        ("Red-Eyes Black Flare Dragon", 2),
        ("Lord of the Red", 1),
        ("Archfiend Black Skull Dragon", 1),
        ("Flame Swordsman", 1),
        ("Dangerous Machine Type-6", 1),
        ("Roulette Spider", 1),
        ("Pot of Greed", 1),
        ("Red-Eyes Fusion", 1),
        ("Cards of the Red Stone", 1),
        ("Red-Eyes Transmigration", 1),
        ("Legendary Sword", 1),
        ("Polymerization", 1),
        ("Time Wizard", 1),
        ("Salamandra", 1),
        ("Scapegoat", 1),
        ("Sixth Sense", 1),
        ("Red-Eyes Spirit", 1),
        ("Gamble", 1),
    ],
    "Duel Opera 2020": [
        ("Red-Eyes Black Dragon", 1),
        ("Black Metal Dragon", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gearfried the Red-Eyes Iron Knight", 1),
        ("Hundred Dragon", 1),
        ("Jinzo", 1),
        ("Marauding Captain", 1),
        ("Time Wizard", 1),
        ("Gilti-Gearfried the Magical Steel Knight", 1),
        ("Red-Eyes Slash Dragon", 1),
        ("Time Wizard of Tomorrow", 1),
        ("Graceful Dice", 1),
        ("Polymerization", 1),
        ("Red-Eyes Fusion", 1),
        ("Foolish Burial", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Skull Dice", 1),
    ],
    "Dark Duel Stories": [
        ("Archfiend Marmot of Nefariousness", 3),
        ("Ancient Jar", 3),
        ("Armed Ninja", 3),
        ("Flame Viper", 3),
        ("Hane-Hane", 3),
        ("Haniwa", 3),
        ("Mountain Warrior", 1),
        ("Muka Muka", 3),
        ("Pot the Trick", 3),
        ("Queen's Double", 3),
        ("Red-Eyes Black Dragon", 1),
        ("Swordsman of Landstar", 1),
        ("Time Wizard", 3),
        ("Dark Hole", 1),
        ("Mooyan Curry", 3),
        ("Sogen", 1),
        ("Sparks", 2),
    ],
    "The Eternal Duelist Soul": [
        ("Alligator's Sword", 3),
        ("Axe Raider", 1),
        ("Baby Dragon", 2),
        ("Battle Steer", 1),
        ("Battle Warrior", 1),
        ("Beaver Warrior", 1),
        ("Blackland Fire Dragon", 1),
        ("Dragon Zombie", 1),
        ("Garoozis", 1),
        ("Hero of the East", 1),
        ("Hitotsu-Me Giant", 2),
        ("Kageningen", 1),
        ("Mystic Horseman", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Summoned Skull", 1),
        ("Tiger Axe", 2),
        ("The 13th Grave", 1),
        ("Torike", 1),
        ("Lava Battleguard", 1),
        ("Panther Warrior", 1),
        ("Swamp Battleguard", 2),
        ("Time Wizard", 1),
        ("Black Skull Dragon", 1),
        ("Thousand Dragon", 1),
        ("Change of Heart", 1),
        ("Graceful Charity", 1),
        ("Heavy Storm", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Raigeki", 1),
        ("Sword of Dragon's Soul", 1),
        ("Magic Jammer", 1),
        ("Magical Arm Shield", 1),
        ("Mirror Force", 1),
        ("Skull Dice", 1),
    ],
    "Worldwide Edition: Stairway to the Destined Duel": [
        ("Alligator's Sword", 3),
        ("Axe Raider", 3),
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Summoned Skull", 3),
        ("Cyber Jar", 1),
        ("Gearfried the Iron Knight", 3),
        ("Goblin Attack Force", 3),
        ("Jinzo", 1),
        ("Panther Warrior", 1),
        ("Time Wizard", 1),
        ("Zombyra the Dark", 3),
        ("Alligator's Sword Dragon", 1),
        ("Black Skull Dragon", 1),
        ("Thousand Dragon", 1),
        ("Change of Heart", 1),
        ("Fusion Sage", 1),
        ("Graceful Charity", 2),
        ("Monster Reborn", 1),
        ("Polymerization", 3),
        ("Premature Burial", 2),
        ("Snatch Steal", 1),
        ("Ring of Destruction", 2),
        ("Magic Jammer", 1),
        ("Magical Arm Shield", 2),
        ("Mirror Force", 1),
    ],
    "Phantom Pyramid": [
        ("Cannon Soldier", 2),
        ("D.D. Warrior", 3),
        ("Needle Worm", 3),
        ("Slate Warrior", 2),
        ("Black Pendant", 1),
        ("Card Destruction", 1),
        ("Chain Energy", 1),
        ("Change of Heart", 1),
        ("Dark Hole", 1),
        ("Final Flame", 1),
        ("Hinotama", 1),
        ("Monster Reborn", 1),
        ("Ookazi", 1),
        ("Raigeki", 1),
        ("Restructer Revolution", 1),
        ("Scapegoat", 3),
        ("Snatch Steal", 1),
        ("Swords of Revealing Light", 1),
        ("Tremendous Fire", 1),
        ("Attack and Receive", 3),
        ("Ring of Destruction", 2),
        ("Ceasefire", 1),
        ("Fairy Box", 1),
        ("Magic Cylinder", 1),
        ("Magical Thorn", 1),
        ("Mirror Force", 1),
        ("Negate Attack", 1),
        ("Trap Hole", 3),
    ],
    "The Falsebound Kingdom - Starter": [
        ("Flame Swordsman", 1),
        ("Giltia the D. Knight", 1),
    ],
    "The Sacred Cards": [
        ("Ancient Jar", 2),
        ("Bat", 3),
        ("Eyearmor", 3),
        ("Jinzo #7", 3),
        ("Masked Clown", 3),
        ("Pot the Trick", 2),
        ("Red-Eyes Black Dragon", 1),
        ("Armed Ninja", 3),
        ("Cyber-Stein", 3),
        ("Gilford the Legend", 1),
        ("Karakuri Spider", 3),
        ("Queen's Double", 3),
        ("Steel Scorpion", 3),
        ("Swordsman from a Distant Land", 3),
        ("Time Wizard", 3),
        ("Metalmorph", 1),
    ],
    "Dark Joey": [
        ("Baby Dragon", 1),
        ("Battle Warrior", 3),
        ("Flame Dancer", 3),
        ("Hinotama Soul", 3),
        ("Mountain Warrior", 3),
        ("Rock Ogre Grotto #1", 3),
        ("Swordsman of Landstar", 3),
        ("Wings of Wicked Flame", 3),
        ("Wolf", 3),
        ("Rocket Warrior", 1),
        ("Time Wizard", 1),
        ("Flame Swordsman", 1),
        ("Final Flame", 2),
        ("Hinotama", 2),
        ("Ookazi", 2),
        ("Salamandra", 1),
        ("Sparks", 2),
        ("Tremendous Fire", 2),
        ("Kunai with Chain", 1),
    ],
    "World Championship 2004": [
        ("Alligator's Sword", 3),
        ("Axe Raider", 3),
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Summoned Skull", 3),
        ("Goblin Attack Force", 2),
        ("Jinzo", 1),
        ("Panther Warrior", 1),
        ("Spear Dragon", 3),
        ("Time Wizard", 3),
        ("Zombyra the Dark", 2),
        ("Alligator's Sword Dragon", 1),
        ("Black Skull Dragon", 1),
        ("Thousand Dragon", 1),
        ("Change of Heart", 1),
        ("Dark Hole", 1),
        ("Fusion Sage", 1),
        ("Graceful Charity", 2),
        ("Mage Power", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 2),
        ("Premature Burial", 2),
        ("Raigeki", 1),
        ("Snatch Steal", 1),
        ("Swords of Revealing Light", 1),
        ("United We Stand", 1),
        ("Mirror Force", 1),
        ("Ring of Destruction", 2),
    ],
    "The Dawn of Destiny": [
        ("Alligator's Sword", 2),
        ("Ansatsu", 1),
        ("Armored Lizard", 1),
        ("Axe Raider", 2),
        ("Baby Dragon", 2),
        ("Battle Steer", 1),
        ("Battle Warrior", 1),
        ("Beautiful Beast Trainer", 1),
        ("Kojikocy", 1),
        ("Meteor Dragon", 3),
        ("Red-Eyes Black Dragon", 2),
        ("Summoned Skull", 2),
        ("Swordsman of Landstar", 1),
        ("Tiger Axe", 2),
        ("Wolf", 1),
        ("Zanki", 1),
        ("Jinzo", 1),
        ("The Legendary Fisherman", 1),
        ("Panther Warrior", 2),
        ("Time Wizard", 2),
        ("Zombyra the Dark", 2),
        ("Alligator's Sword Dragon", 2),
        ("Black Skull Dragon", 2),
        ("Meteor Black Dragon", 1),
        ("Thousand Dragon", 2),
        ("Axe of Despair", 2),
        ("Change of Heart", 1),
        ("Fusion Sage", 2),
        ("Graceful Charity", 1),
        ("Mage Power", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 2),
        ("Snatch Steal", 1),
        ("United We Stand", 1),
        ("Mirror Force", 1),
    ],
    "Reshef of Destruction": [
        ("Baby Dragon", 1),
        ("Battle Warrior", 3),
        ("Dancing Elf", 3),
        ("Jinzo #7", 3),
        ("Kagemusha of the Blue Flame", 3),
        ("Mountain Warrior", 3),
        ("Red-Eyes Black Dragon", 1),
        ("Swordsman of Landstar", 3),
        ("Armed Ninja", 3),
        ("Magician of Faith", 3),
        ("Queen's Double", 3),
        ("The Unhappy Maiden", 3),
        ("Time Wizard", 3),
        ("Flame Swordsman", 1),
        ("Thousand Dragon", 1),
        ("Salamandra", 1),
        ("Eatgaboon", 1),
        ("Kunai with Chain", 1),
    ],
    "Reshef of Destruction - Possessed": [
        ("Red-Eyes Black Dragon", 1),
        ("Steel Fan Fighter [R]", 1),
        ("Boar Soldier", 3),
        ("Exarion Universe", 1),
        ("Gearfried the Iron Knight", 3),
        ("Gilford the Lightning", 1),
        ("Jinzo", 1),
        ("Panther Warrior", 3),
        ("Red-Eyes Black Metal Dragon", 1),
        ("Zombyra the Dark", 3),
        ("Black Skull Dragon", 1),
        ("Change of Heart", 3),
        ("Harpie's Feather Duster", 3),
        ("Megamorph", 3),
        ("Monster Reborn", 3),
        ("Pot of Greed", 3),
        ("Swords of Revealing Light", 3),
        ("Torrential Tribute", 3),
    ],
    "7 Trials to Glory: Standard": [
        ("Alligator's Sword", 3),
        ("Axe Raider", 3),
        ("Baby Dragon", 3),
        ("Kojikocy", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Summoned Skull", 2),
        ("Goblin Attack Force", 1),
        ("Hane-Hane", 1),
        ("Man-Eater Bug", 1),
        ("Panther Warrior", 1),
        ("Penguin Soldier", 1),
        ("Spear Dragon", 3),
        ("Time Wizard", 3),
        ("Zombyra the Dark", 1),
        ("Alligator's Sword Dragon", 1),
        ("Black Skull Dragon", 1),
        ("Change of Heart", 1),
        ("Fusion Sage", 1),
        ("Graceful Charity", 1),
        ("Graceful Dice", 1),
        ("Polymerization", 2),
        ("Premature Burial", 1),
        ("Raigeki", 1),
        ("Magic Jammer", 1),
        ("Mirror Force", 1),
        ("Seven Tools of the Bandit", 1),
        ("Skull Dice", 1),
        ("Torrential Tribute", 1),
    ],
    "7 Trials to Glory: Advanced": [
        ("Archfiend Soldier", 3),
        ("Gemini Elf", 3),
        ("Luster Dragon #2", 3),
        ("Mad Dog of Darkness", 3),
        ("Summoned Skull", 1),
        ("Vorse Raider", 3),
        ("Cave Dragon", 3),
        ("Giant Orc", 3),
        ("Granadora", 3),
        ("Goblin Attack Force", 3),
        ("Jinzo", 1),
        ("Slate Warrior", 1),
        ("Spear Dragon", 3),
        ("Spell Canceller", 3),
        ("Zombyra the Dark", 3),
        ("Axe of Despair", 3),
        ("Card Destruction", 1),
        ("Dark Hole", 1),
        ("United We Stand", 1),
        ("Ring of Destruction", 1),
    ],
    "Warrior Max": [
        ("Alligator's Sword", 1),
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 2),
        ("D.D. Assailant", 1),
        ("D.D. Warrior Lady", 1),
        ("Double Coston", 2),
        ("Gearfried the Iron Knight", 3),
        ("Gilford the Lightning", 1),
        ("Jinzo", 1),
        ("Marauding Captain", 2),
        ("Black Dragon's Chick", 2),
        ("Rocket Warrior", 2),
        ("Time Wizard", 1),
        ("Versago the Destroyer", 1),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Book of Moon", 1),
        ("Creature Swap", 1),
        ("Fusion Gate", 1),
        ("Graceful Charity", 1),
        ("Heavy Storm", 1),
        ("Lightning Vortex", 1),
        ("Mystical Space Typhoon", 1),
        ("Nobleman of Crossout", 1),
        ("Premature Burial", 1),
        ("Reinforcement of the Army", 1),
        ("Rush Recklessly", 1),
        ("Shrink", 1),
        ("Smashing Ground", 1),
        ("The Warrior Returning Alive", 1),
        ("Twister", 1),
        ("Call of the Haunted", 1),
        ("Magical Arm Shield", 1),
        ("Mirror Force", 1),
        ("Ring of Destruction", 1),
    ],
    "Display of Courage": [
        ("Alligator's Sword", 1),
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 2),
        ("D.D. Assailant", 1),
        ("D.D. Warrior Lady", 1),
        ("Double Coston", 2),
        ("Gearfried the Iron Knight", 3),
        ("Gilford the Lightning", 1),
        ("Jinzo", 1),
        ("Marauding Captain", 2),
        ("Black Dragon's Chick", 2),
        ("Rocket Warrior", 2),
        ("Time Wizard", 1),
        ("Versago the Destroyer", 1),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Book of Moon", 1),
        ("Creature Swap", 1),
        ("Fusion Gate", 1),
        ("Heavy Storm", 1),
        ("Lightning Vortex", 1),
        ("Mystical Space Typhoon", 1),
        ("Nobleman of Crossout", 1),
        ("Pot of Avarice", 1),
        ("Premature Burial", 1),
        ("Reinforcement of the Army", 1),
        ("Rush Recklessly", 1),
        ("Shrink", 1),
        ("Smashing Ground", 1),
        ("The Warrior Returning Alive", 1),
        ("Twister", 1),
        ("Call of the Haunted", 1),
        ("Magical Arm Shield", 1),
        ("Mirror Force", 1),
        ("Sakuretsu Armor", 1),
    ],
    "Ideal Partner": [
        ("Alligator's Sword", 1),
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 2),
        ("D.D. Assailant", 1),
        ("D.D. Warrior Lady", 1),
        ("Double Coston", 2),
        ("Gearfried the Iron Knight", 3),
        ("Gilford the Lightning", 1),
        ("Jinzo", 1),
        ("Marauding Captain", 2),
        ("Black Dragon's Chick", 2),
        ("Rocket Warrior", 2),
        ("Time Wizard", 1),
        ("Versago the Destroyer", 1),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Book of Moon", 1),
        ("Creature Swap", 1),
        ("Fusion Gate", 1),
        ("Heavy Storm", 1),
        ("Lightning Vortex", 1),
        ("Mystical Space Typhoon", 1),
        ("Nobleman of Crossout", 1),
        ("Premature Burial", 1),
        ("Reinforcement of the Army", 2),
        ("Rush Recklessly", 1),
        ("Shrink", 1),
        ("Smashing Ground", 1),
        ("The Warrior Returning Alive", 1),
        ("Twister", 1),
        ("Call of the Haunted", 1),
        ("Magical Arm Shield", 1),
        ("Mirror Force", 1),
        ("Widespread Ruin", 1),
    ],
    "Dice Power": [
        ("Alligator's Sword", 2),
        ("Axe Raider", 2),
        ("Baby Dragon", 3),
        ("Battle Warrior", 2),
        ("Garoozis", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Tiger Axe", 2),
        ("Gilford the Lightning", 1),
        ("Little-Winguard", 1),
        ("Panther Warrior", 1),
        ("Red-Eyes Black Metal Dragon", 1),
        ("Rocket Warrior", 1),
        ("Time Wizard", 3),
        ("Versago the Destroyer", 1),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Dangerous Machine TYPE-6", 2),
        ("Emergency Provisions", 1),
        ("Graceful Dice", 2),
        ("Polymerization", 2),
        ("Pot of Greed", 1),
        ("Blind Destruction", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
        ("Magical Arm Shield", 1),
        ("Metalmorph", 2),
        ("Needle Wall", 2),
        ("Skull Dice", 2),
    ],
    "Power of Luck": [
        ("Alligator's Sword", 2),
        ("Axe Raider", 2),
        ("Baby Dragon", 3),
        ("Battle Warrior", 1),
        ("Kojikocy", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Tiger Axe", 2),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Panther Warrior", 1),
        ("Red-Eyes Black Metal Dragon", 1),
        ("Rocket Warrior", 2),
        ("Time Wizard", 3),
        ("Versago the Destroyer", 1),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Dangerous Machine TYPE-6", 2),
        ("Emergency Provisions", 1),
        ("Graceful Dice", 2),
        ("Polymerization", 2),
        ("Pot of Greed", 1),
        ("Fairy Box", 1),
        ("Graverobber", 2),
        ("Kunai with Chain", 1),
        ("Magical Arm Shield", 1),
        ("Metalmorph", 2),
        ("Needle Wall", 2),
        ("Skull Dice", 1),
    ],
    "Warrior Max v1": [
        ("Alligator's Sword", 2),
        ("Axe Raider", 2),
        ("Baby Dragon", 1),
        ("Kojikocy", 1),
        ("Red-Eyes Black Dragon", 1),
        ("D.D. Assailant", 1),
        ("D.D. Warrior", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Goblin Attack Force", 1),
        ("Jinzo", 1),
        ("Little-Winguard", 1),
        ("Marauding Captain", 1),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 1),
        ("Time Wizard", 2),
        ("Versago the Destroyer", 1),
        ("Zombyra the Dark", 1),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Cost Down", 1),
        ("Dangerous Machine TYPE-6", 2),
        ("Fusion Gate", 1),
        ("Graceful Charity", 1),
        ("Graceful Dice", 2),
        ("Legendary Sword", 1),
        ("Pot of Greed", 1),
        ("Reinforcement of the Army", 1),
        ("Scapegoat", 2),
        ("Call of the Haunted", 1),
        ("Fairy Box", 1),
        ("Graverobber", 1),
        ("Kunai with Chain", 1),
        ("Magical Arm Shield", 1),
        ("Skull Dice", 2),
    ],
    "Warrior Max v2": [
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 1),
        ("D.D. Assailant", 2),
        ("D.D. Warrior Lady", 1),
        ("Exiled Force", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Goblin Attack Force", 1),
        ("Jinzo", 1),
        ("Marauding Captain", 2),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 2),
        ("Sasuke Samurai #4", 1),
        ("Time Wizard", 1),
        ("Versago the Destroyer", 1),
        ("Zombyra the Dark", 3),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Cost Down", 1),
        ("Dangerous Machine TYPE-6", 1),
        ("Fusion Gate", 1),
        ("Graceful Charity", 1),
        ("Graceful Dice", 1),
        ("Lightning Vortex", 1),
        ("Pot of Greed", 1),
        ("Reinforcement of the Army", 2),
        ("Scapegoat", 1),
        ("The A. Forces", 1),
        ("United We Stand", 1),
        ("Call of the Haunted", 1),
        ("Fairy Box", 2),
        ("Kunai with Chain", 1),
        ("Metalmorph", 1),
        ("Sixth Sense", 1),
        ("Skull Dice", 1),
    ],
    "Super Warrior": [
        ("Command Knight", 3),
        ("D.D. Assailant", 2),
        ("D.D. Warrior Lady", 1),
        ("Exiled Force", 1),
        ("Don Zaloog", 2),
        ("Gilford the Lightning", 2),
        ("Goblin Attack Force", 2),
        ("Marauding Captain", 2),
        ("Sasuke Samurai", 1),
        ("The Fiend Megacyber", 2),
        ("Zombyra the Dark", 2),
        ("Fusion Sword Murasame Blade", 2),
        ("Graceful Charity", 1),
        ("Mage Power", 1),
        ("Mystical Space Typhoon", 1),
        ("Pot of Greed", 1),
        ("Reinforcement of the Army", 2),
        ("Scapegoat", 1),
        ("The A. Forces", 3),
        ("The Warrior Returning Alive", 2),
        ("United We Stand", 1),
        ("Call of the Haunted", 1),
        ("Dust Tornado", 1),
        ("Mirror Force", 1),
        ("Raigeki Break", 1),
        ("Ring of Destruction", 1),
    ],
    "Duel Gambler": [
        ("Alligator's Sword", 1),
        ("Axe Raider", 1),
        ("Baby Dragon", 1),
        ("Red-Eyes Black Dragon", 1),
        ("D.D. Assailant", 2),
        ("D.D. Warrior Lady", 1),
        ("Gearfried the Iron Knight", 1),
        ("Gilford the Lightning", 1),
        ("Goblin Attack Force", 1),
        ("Jinzo", 1),
        ("Marauding Captain", 2),
        ("Panther Warrior", 1),
        ("Rocket Warrior", 2),
        ("Sasuke Samurai #4", 1),
        ("Time Wizard", 1),
        ("Versago the Destroyer", 1),
        ("Zombyra the Dark", 2),
        ("Alligator's Sword Dragon", 3),
        ("Black Skull Dragon", 3),
        ("Thousand Dragon", 3),
        ("Cost Down", 1),
        ("Dangerous Machine TYPE-6", 1),
        ("Fusion Gate", 1),
        ("Graceful Charity", 1),
        ("Graceful Dice", 2),
        ("Pot of Greed", 1),
        ("Reinforcement of the Army", 2),
        ("Scapegoat", 2),
        ("The A. Forces", 1),
        ("Call of the Haunted", 1),
        ("Fairy Box", 1),
        ("Graverobber", 1),
        ("Magical Arm Shield", 1),
        ("Metalmorph", 1),
        ("Sixth Sense", 1),
        ("Skull Dice", 1),
    ],
    "Duel Terminal": [
        ("Alligator's Sword", 1),
        ("Little-Winguard", 1),
        ("Time Wizard", 1),
        ("Graceful Dice", 1),
        ("Skull Dice", 1),
    ],
}