KAIBA_DECKS = {
    "Toei - First Series": [
        ("Battle Ox", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Blue-Eyes White Dragon's 3-Body Connection [A]", 1),
        ("Grappler", 1),
        ("Dark Zorla [A]", 1),
        ("Gremlin [A]", 1),
        ("Hitotsu-Me Giant", 1),
        ("Ryu-Kishin", 1),
        ("Saggi the Dark Clown", 1),
        ("The Wicked Worm Beast", 1),
        ("Dark Energy", 1),
        ("Megamorph", 1),
        ("Stop Defense", 1),
        ("Wicked Chain", 1),
    ],
    "Childhood Deck": [
        ("Baby Dragon", 1),
        ("Basic Insect", 1),
        ("Blue-Eyes White Dragon", 1),
        ("Gemini Elf", 1),
        ("Niwatori", 1),
        ("Saggi the Dark Clown", 1),
        ("The Furious Sea King", 1),
        ("Torike", 1),
    ],
    "Duelist Kingdom": [
        ("Aqua Madoor", 1),
        ("Battle Ox", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Grappler", 1),
        ("Gyakutenno Megami", 1),
        ("Hitotsu-Me Giant", 1),
        ("Judge Man", 1),
        ("La Jinn the Mystical Genie of the Lamp", 1),
        ("Mystic Horseman", 1),
        ("Rude Kaiser", 1),
        ("Ryu-Kishin Powered", 1),
        ("Saggi the Dark Clown", 1),
        ("Cyber Jar", 1),
        ("Lord of D.", 1),
        ("Swordstalker", 1),
        ("Trap Master", 1),
        ("Wall of Illusion", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Rabid Horseman", 1),
        ("De-Spell", 2),
        ("Gift of the Mystical Elf", 1),
        ("Mesmeric Control", 1),
        ("Monster Reborn", 1),
        ("Negate Attack", 1),
        ("Negative Energy Generator [A]", 1),
        ("Polymerization", 1),
        ("Shadow Spell", 1),
        ("The Flute of Summoning Dragon", 1),
        ("Ancient Lamp", 1),
        ("Crush Card Virus", 1),
        ("Stop Defense", 1),
    ],
    "Test Deck": [
        ("Battle Ox", 1),
        ("Hitotsu-Me Giant", 1),
        ("Boar Soldier", 1),
        ("Dark Zebra", 1),
        ("Dragon Seeker", 1),
        ("D.D. Warrior", 1),
        ("Maha Vailo", 1),
        ("Obelisk the Tormentor", 1),
    ],
    "Battle City": [
        ("Battle Ox", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Des Feral Imp", 1),
        ("Gadget Soldier", 1),
        ("Hyozanryu", 1),
        ("La Jinn the Mystical Genie of the Lamp", 1),
        ("Ryu-Kishin Powered", 1),
        ("Saggi the Dark Clown", 1),
        ("Swordstalker", 1),
        ("Vorse Raider", 1),
        ("X-Head Cannon", 1),
        ("Blade Knight", 1),
        ("Kaiser Glider", 1),
        ("Kaiser Sea Horse", 1),
        ("Lord of D.", 1),
        ("Masked Beast Des Gardius", 1),
        ("Obelisk the Tormentor", 1),
        ("Sword of Soul [A]", 1),
        ("Thunder Dragon", 3),
        ("Y-Dragon Head", 1),
        ("Z-Metal Tank", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Twin-Headed Thunder Dragon", 1),
        ("XY-Dragon Cannon", 1),
        ("XYZ-Dragon Cannon", 1),
        ("Spell Absorption", 1),
        ("Card Guard", 1),
        ("Card of Demise", 1),
        ("Command Silencer [A]", 1),
        ("Cost Down", 1),
        ("Enemy Controller", 1),
        ("Fiend's Sanctuary", 1),
        ("Interdimensional Matter Transporter", 1),
        ("Lullaby of Obedience", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Quick Attack [A]", 1),
        ("Shadow Spell", 1),
        ("Ring of Defense", 1),
        ("Shrink", 1),
        ("Silent Doom", 1),
        ("Soul Exchange", 1),
        ("Spell Sanctuary [A]", 1),
        ("Stop Defense", 1),
        ("The Flute of Summoning Dragon", 2),
        ("Thirst for Compensation [A]", 1),
        ("Virus Cannon", 1),
        ("Attack Guidance Armor", 1),
        ("Cloning", 1),
        ("Crush Card Virus", 1),
        ("Final Attack Orders", 1),
        ("Magical Trick Mirror", 1),
        ("Power Balance [A]", 1),
        ("Ring of Destruction", 1),
    ],
    "Virtual World": [
        ("Blue-Eyes White Dragon", 3),
        ("Hyozanryu", 1),
        ("La Jinn the Mystical Genie of the Lamp", 1),
        ("Luster Dragon #2", 1),
        ("Vorse Raider", 1),
        ("Zoa", 1),
        ("Ancient Lamp", 1),
        ("Cave Dragon", 1),
        ("Cyber Jar", 1),
        ("Different Dimension Dragon", 1),
        ("Kaiser Glider", 1),
        ("Giant Germ", 2),
        ("Kaiser Sea Horse", 1),
        ("Lord of D.", 1),
        ("Possessed Dark Soul", 1),
        ("Slate Warrior", 1),
        ("Spear Dragon", 1),
        ("Spirit Ryu", 1),
        ("The Wicked Worm Beast", 1),
        ("Thunder Dragon", 3),
        ("Twin-Headed Behemoth", 1),
        ("Vampire Lord", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Twin-Headed Thunder Dragon", 1),
        ("A Wingbeat of Giant Dragon", 1),
        ("De-Fusion", 1),
        ("Double Snare", 1),
        ("Heavy Storm", 1),
        ("Magic Reflector", 1),
        ("Monster Reborn", 1),
        ("Negate Attack", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Quick Attack [A]", 1),
        ("Ring of Defense", 1),
        ("Shrink", 1),
        ("The Flute of Summoning Dragon", 1),
        ("Burst Breath", 1),
        ("Crush Card Virus", 1),
        ("Dragon's Rage", 1),
        ("Last Turn", 1),
        ("Ring of Destruction", 1),
        ("Soul Demolition", 1),
    ],
    "Waking the Dragons": [
        ("Blue-Eyes White Dragon", 3),
        ("Gadget Soldier", 1),
        ("Judge Man", 1),
        ("Vorse Raider", 1),
        ("X-Head Cannon", 1),
        ("Blade Knight", 1),
        ("Different Dimension Dragon", 1),
        ("Kaiser Glider", 1),
        ("Kaiser Sea Horse", 1),
        ("Spear Dragon", 1),
        ("Versago the Destroyer", 1),
        ("Pitch-Dark Dragon", 1),
        ("Y-Dragon Head", 1),
        ("Z-Metal Tank", 1),
        ("Paladin of White Dragon", 1),
        ("Blue-Eyes Tyrant Dragon", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("XYZ-Dragon Cannon", 1),
        ("Doom Virus Dragon", 1),
        ("Mirror Force Dragon", 1),
        ("Tyrant Burst Dragon", 1),
        ("A Wingbeat of Giant Dragon", 1),
        ("Card of Demise", 1),
        ("Charm of Lamentation [A]", 1),
        ("Cost Down", 1),
        ("Monster Reborn", 1),
        ("Negate Attack", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Reflect Energy [A]", 1),
        ("Shrink", 1),
        ("Silent Doom", 1),
        ("Soul Exchange", 1),
        ("White Dragon Ritual", 1),
        ("The Fang of Critias", 1),
        ("Attack Guidance Barrier [A]", 1),
        ("Cloning", 1),
        ("Crush Card Virus", 1),
        ("Magical Trick Mirror", 1),
        ("Ring of Destruction", 1),
        ("Tyrant Wing", 1),
        ("Wish of Final Effort [A]", 1),
    ],
    "Grand Championship": [
        ("Blue-Eyes White Dragon", 3),
        ("Luster Dragon #2", 1),
        ("X-Head Cannon", 1),
        ("Cave Dragon", 1),
        ("Chaos Emperor Dragon - Envoy of the End", 1),
        ("Clone Dragon [A]", 1),
        ("Pitch-Dark Dragon", 1),
        ("Y-Dragon Head", 1),
        ("Z-Metal Tank", 1),
        ("XYZ-Dragon Cannon", 1),
        ("Spell Absortion", 1),
        ("Card of Demise", 1),
        ("Cost Down", 1),
        ("De-Fusion", 1),
        ("Dimension Fusion", 1),
        ("Emergency Provisions", 1),
        ("Graceful Charity", 1),
        ("Monster Reborn", 1),
        ("Negate Attack", 1),
        ("Pot of Greed", 1),
        ("Shrink", 1),
        ("Soul Absorption", 1),
        ("Soul Release", 1),
        ("Spell Reproduction", 1),
        ("Attack Guidance Armor", 1),
        ("Cloning", 1),
        ("Flat Lv 4 [A]", 1),
        ("Magical Trick Mirror", 1),
    ],
    "Dawn of the Duel": [
        ("Blue-Eyes White Dragon", 3),
        ("Vorse Raider", 1),
        ("Lord of D.", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Card of Demise", 1),
        ("Monster Reborn", 1),
        ("Ring of Defense", 1),
        ("Shrink", 1),
        ("Silent Doom", 1),
        ("Soul Release", 1),
        ("The Flute of Summoning Dragon", 1),
        ("Attack Guidance Armor", 1),
        ("Cloning", 1),
    ],
    "First Briefcase": [
        ("Air Eater", 1),
        ("Anthrosaurus", 1),
        ("B. Dragon Jungle King", 1),
        ("Battle Steer", 1),
        ("Bolt Escargot", 1),
        ("Boulder Tortoise", 1),
        ("Cyber Soldier", 1),
        ("Flame Cerebrus", 1),
        ("Launcher Spider", 1),
        ("Millennium Golem", 1),
        ("Monstrous Bird", 1),
        ("Royal Guard", 1),
        ("Sea King Dragon", 1),
        ("Togex", 1),
        ("Empress Judge", 1),
        ("Giltia the D. Knight", 1),
        ("Labyrinth Tank", 1),
        ("Punished Eagle", 1),
        ("Roaring Ocean Snake", 1),
        ("Skelgon", 1),
        ("Block Attack", 1),
        ("Mooyan Curry", 1),
        ("Polymerization", 1),
        ("Red Medicine", 1),
        ("Remove Trap", 1),
    ],
    "Second Briefcase": [
        ("Armored Lizard", 1),
        ("Axe Raider", 1),
        ("Basic Insect", 1),
        ("Big Insect", 1),
        ("Crawling Dragon", 1),
        ("Cyber Commander", 1),
        ("Flying Elephant", 1),
        ("Garnecia Elefantis", 1),
        ("Garoozis", 1),
        ("Gokibore", 1),
        ("Grappler", 1),
        ("Gyakutenno Megami", 1),
        ("Hitotsu-Me Giant", 1),
        ("Illusionist Faceless Mage", 1),
        ("Kamakiriman", 1),
        ("Kairyu-Shin", 1),
        ("Killer Needle", 1),
        ("Masaki the Legendary Swordsman", 1),
        ("Mystic Horseman", 1),
        ("Red-Eyes Black Dragon", 1),
        ("Tiger Axe", 1),
        ("Torike", 1),
        ("Trakodon", 1),
        ("Castle of Dark Illusions", 1),
        ("Great Moth", 1),
        ("Lava Battleguard", 1),
        ("Magician of Faith", 1),
        ("Swamp Battleguard", 1),
        ("Rabid Horseman", 1),
        ("Change of Heart", 1),
        ("Cyber Shield", 1),
        ("Laser Cannon Armor", 1),
        ("Stop Defense", 1),
    ],
    "Third Briefcase": [
        ("Alligator's Sword", 1),
        ("Gyakutenno Megami", 1),
        ("Hyozanryu", 1),
        ("Swordsman of Landstar", 1),
        ("Zoa", 1),
        ("Metalzoa", 1),
        ("Panther Warrior", 1),
        ("The Fiend Megacyber", 1),
        ("Breath of Light", 1),
        ("Graceful Charity", 2),
        ("Graceful Dice", 1),
        ("Harpie's Feather Duster", 1),
        ("Invigoration", 1),
        ("Magical Neutralizing Force Field [A]", 1),
        ("Mesmeric Control", 1),
        ("Chain Destruction", 1),
        ("Skull Dice", 1),
        ("Tears of a Mermaid [A]", 1),
    ],
    "Fourth Briefcase": [
        ("Blue-Eyes White Dragon", 1),
        ("Curse of Dragon", 1),
        ("Vorse Raider", 2),
        ("X-Head Cannon", 1),
        ("Different Dimension Dragon", 1),
        ("Kaiser Glider", 1),
        ("Lord of D.", 1),
        ("Spear Dragon", 1),
        ("Dark Ruler Ha Des", 1),
        ("Pitch-Dark Dragon", 1),
        ("Y-Dragon Head", 1),
        ("Z-Metal Tank", 1),
        ("Paladin of White Dragon", 1),
        ("Dragon Master Knight", 1),
        ("XYZ-Dragon Cannon", 1),
        ("A Wingbeat of Giant Dragon", 1),
        ("Cost Down", 1),
        ("De-Fusion", 1),
        ("Emergency Provisions", 1),
        ("Monster Reborn", 1),
        ("Mystical Space Typhoon", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Shrink", 1),
        ("Silent Doom", 1),
        ("Soul Absorption", 1),
        ("Swords of Revealing Light", 1),
        ("The Flute of Summoning Dragon", 1),
        ("Attack Guidance Armor", 1),
        ("Cloning", 1),
        ("Magical Trick Mirror", 1),
        ("Negate Attack", 1),
        ("Ring of Destruction", 1),
    ],
    "Fifth Briefcase": [
        ("Beast of Talwar", 1),
        ("Dark Blade", 1),
        ("Black Tyranno", 1),
        ("Chaos Emperor Dragon - Envoy of the End", 1),
        ("Chaosrider Gustaph", 1),
        ("Darkbishop Archfiend", 1),
        ("Don Zaloog", 1),
        ("D.D. Warrior Lady", 1),
        ("Fushioh Richie", 1),
        ("Great Dezard", 1),
        ("Guardian Sphinx", 1),
        ("Hannibal Necromancer", 1),
        ("Insect Princess", 1),
        ("Invader of Darkness", 1),
        ("Maximum Six", 1),
        ("Mystical Knight of Jackal", 1),
        ("Terrorking Archfiend", 1),
        ("Victory Dragon", 1),
        ("Legendary Flame Lord", 1),
        ("Cost Down", 1),
        ("D.D. Designator", 1),
        ("Dangerous Machine Type-6", 1),
        ("Soul Taker", 1),
        ("Big Burn", 1),
        ("Cloning", 1),
        ("Coffin Seller", 1),
        ("Dark Mirror Force", 1),
        ("Judgment of Anubis", 1),
        ("Sixth Sense", 1),
        ("Spell Shield Type-8", 1),
    ],
    "Early Manga": [
        ("Battle Ox", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Hitotsu-me Giant", 1),
        ("Judge Man", 1),
        ("Saggi the Dark Clown", 1),
        ("Ryu-Kishin", 1),
        ("The Wicked Worm Beast", 1),
        ("Dark Energy", 1),
        ("Megamorph", 1),
    ],
    "Manga - Duelist Kingdom": [
        ("Battle Ox", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Grappler", 1),
        ("La Jinn the Mystical Genie of the Lamp", 1),
        ("Mystic Horseman", 1),
        ("Rude Kaiser", 1),
        ("Ryu-Kishin Powered", 1),
        ("Saggi the Dark Clown", 1),
        ("Lord of D.", 1),
        ("Swordstalker", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Rabid Horseman", 1),
        ("Gift of the Mystical Elf", 1),
        ("Mesmeric Control", 1),
        ("Monster Reborn", 1),
        ("Negate Attack", 1),
        ("Polymerization", 1),
        ("Shadow Spell", 1),
        ("The Flute of Summoning Dragon", 1),
        ("Ancient Lamp", 1),
        ("Stop Defense", 1),
        ("Crush Card Virus", 1),
    ],
    "Manga - Test Deck": [
        ("Invitation to a Dark Sleep", 1),
        ("Steel Ogre Grotto #2", 1),
        ("Obelisk the Tormentor", 1),
        ("Monster Reborn", 1),
        ("Negate Attack", 1),
    ],
    "Manga - Battle City": [
        ("Blade Knight", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Des Feral Imp", 1),
        ("Gadget Soldier", 1),
        ("Kaiser Glider", 1),
        ("Vorse Raider", 1),
        ("X-Head Cannon", 1),
        ("Y-Dragon Head", 1),
        ("Z-Metal Tank", 1),
        ("Lord of D.", 1),
        ("Obelisk the Tormentor", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("XY-Dragon Cannon", 1),
        ("XYZ-Dragon Cannon", 1),
        ("Card of Demise", 1),
        ("Cost Down", 1),
        ("Fiend's Sanctuary", 1),
        ("Enemy Controller", 1),
        ("Interdimensional Matter Transporter", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Shrink", 1),
        ("Silent Doom", 1),
        ("Soul Exchange", 1),
        ("The Flute of Summoning Dragon", 1),
        ("Lullaby of Obedience", 1),
        ("Spell Absortion", 1),
        ("Attack Guidance Armor", 1),
        ("Cloning", 1),
        ("Crush Card Virus", 1),
        ("Final Attack Orders", 1),
        ("Magical Trick Mirror", 1),
        ("Ring of Destruction", 1),
        ("Virus Cannon", 1),
    ],
    "Yu-Gi-Oh! R": [
        ("Blade Knight", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Material Armadillo [M]", 1),
        ("Material Bat [M]", 1),
        ("Material Lion [M]", 1),
        ("Material Scorpion [M]", 1),
        ("Swordstalker", 1),
        ("Vorse Raider", 1),
        ("Lord of D.", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Mosaic Manticore", 1),
        ("Alpha-Wave Emission [M]", 1),
        ("Cost Down", 1),
        ("Cross Shift [M]", 1),
        ("Polymerization", 1),
        ("Shrink", 1),
        ("Silent Doom", 1),
        ("The Flute of Summoning Dragon", 1),
        ("The Melody of Awakening Dragon", 1),
        ("Vaccination [M]", 1),
        ("Crush Card Virus", 1),
        ("Magical Trick Mirror", 1),
    ],
    "Yu-Gi-Oh! GX": [
        ("Blue-Eyes White Dragon", 3),
        ("Swordstalker", 1),
        ("Different Dimension Dragon", 1),
        ("Kaibaman", 1),
        ("Kaiser Sea Horse", 1),
        ("Lord of D.", 1),
        ("Manju of the Ten Thousand Hands", 1),
        ("Paladin of White Dragon", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Burst Stream of Destruction", 1),
        ("Cost Down", 1),
        ("De-Fusion", 1),
        ("Fiend's Sanctuary", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Silent Doom", 1),
        ("White Dragon Ritual", 1),
        ("Crush Card Virus", 1),
    ],
    "Pyramid of Light": [
        ("Blue-Eyes White Dragon", 3),
        ("Luster Dragon", 2),
        ("Vorse Raider", 1),
        ("X-Head Cannon", 1),
        ("Blue-Eyes Shining Dragon", 1),
        ("Des Feral Imp", 1),
        ("Familiar Knight", 1),
        ("Kaiser Sea Horse", 1),
        ("Lord of D.", 1),
        ("Peten the Dark Clown", 3),
        ("Rare Metal Dragon", 1),
        ("Spear Dragon", 2),
        ("Y-Dragon Head", 1),
        ("Z-Metal Tank", 1),
        ("Paladin of White Dragon", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("XYZ-Dragon Cannon", 1),
        ("Card of Demise", 1),
        ("Cost Down", 1),
        ("Dark Core", 1),
        ("De-Fusion", 1),
        ("Dimension Fusion", 1),
        ("Enemy Controller", 1),
        ("Megamorph", 1),
        ("Monster Reborn", 1),
        ("Mystical Space Typhoon", 1),
        ("Nobleman of Crossout", 1),
        ("Obligatory Summon [A]", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Soul Release", 1),
        ("The Flute of Summoning Dragon", 1),
        ("White Dragon Ritual", 1),
        ("Attack Guidance Armor", 1),
        ("Cloning", 1),
        ("Deck Destruction Virus [A]", 1),
        ("Pyramid of Light", 1),
        ("Return from the Different Dimension", 1),
        ("Ring of Destruction", 1),
    ],
    "The Dark Side of Dimensions": [
        ("Blue-Eyes White Dragon", 3),
        ("Saggi the Dark Clown", 1),
        ("Assault Wyvern", 1),
        ("Blue-Eyes Alternative White Dragon", 1),
        ("Deep-Eyes White Dragon", 1),
        ("Kaiser Vorse Raider", 1),
        ("Krystal Dragon", 2),
        ("Lord of D.", 1),
        ("Obelisk the Tormentor", 1), #Check Wiki Notes for this one
        ("Pandemic Dragon", 1),
        ("Blue-Eyes Chaos MAX Dragon", 1),
        ("Neo Blue-Eyes Ultimate Dragon", 1),
        ("Chaos Form", 1),
        ("Dragon's Fighting Spirit", 1),
        ("Polymerization", 1),
        ("Counter Gate", 1),
        ("Dark Sacrifice", 1),
        ("Dragon's Orb [A]", 1),
        ("Enhanced Counter [A]", 1),
        ("High Speed Aria [A]", 1),
        ("Induced Explosion", 1),
        ("Krystal Avatar", 1),
    ],
    "North American World Championship Qualifiers 2012": [
        ("Alexandrite Dragon", 1),
        ("Battle Ox", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Ryu-Kishin", 1),
        ("Vorse Raider", 1),
        ("Cyber Jar", 1),
        ("Lord of D.", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("A Wingbeat of Giant Dragon", 1),
        ("De-Spell", 1),
        ("Dimension Fusion", 1),
        ("Enemy Controller", 1),
        ("Graceful Charity", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Soul Absorption", 1),
        ("The Flute of Summoning Dragon", 1),
        ("Crush Card Virus", 1),
        ("Gift of The Mystical Elf", 1),
        ("Negate Attack", 1),
        ("Soul Demolition", 1),
    ],
    "North American World Championship Qualifiers 2013": [
        ("Blue-Eyes White Dragon", 3),
        ("Hitotsu-me Giant", 1),
        ("La Jinn the Mystical Genie of the Lamp", 1),
        ("Luster Dragon #2", 1),
        ("Chaos Emperor Dragon - Envoy of the End", 1),
        ("Cyber Jar", 1),
        ("Lord of D.", 1),
        ("Slate Warrior", 1),
        ("Maiden with Eyes of Blue", 1),
        ("The White Stone of Legend", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("De-Fusion", 1),
        ("Dragon Shrine", 1),
        ("Enemy Controller", 1),
        ("Graceful Charity", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Ring of Defense", 1),
        ("Shard of Greed", 1),
        ("Shrink", 1),
        ("Silver's Cry", 2),
        ("Trade-In", 1),
        ("Ancient Lamp", 1),
        ("Castle of Dragon Souls", 1),
        ("Negate Attack", 1),
        ("Return from the Different Dimension", 1),
        ("Ring of Destruction", 1),
        ("Shadow Spell", 1),
    ],
    "World Championship 2016 Special": [
        ("Alexandrite Dragon", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Luster Dragon", 1),
        ("Blue-Eyes Alternative White Dragon", 1),
        ("Chaos Emperor Dragon - Envoy of the End", 1),
        ("Kaiser Vorse Raider", 1),
        ("Maiden with Eyes of Blue", 1),
        ("Sage with Eyes of Blue", 1),
        ("The White Stone of Ancients", 1),
        ("Blue-Eyes Twin Burst Dragon", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Neo Blue-Eyes Ultimate Dragon", 1),
        ("Blue-Eyes Spirit Dragon", 1),
        ("Azure-Eyes Silver Dragon", 1),
        ("A Wingbeat of Giant Dragon", 1),
        ("Card of Demise", 1),
        ("Cards of Consonance", 1),
        ("De-Fusion", 1),
        ("Dragon's Mirror", 1),
        ("Enemy Controller", 1),
        ("Lullaby of Obedience", 1),
        ("Mausoleum of White", 1),
        ("Polymerization", 1),
        ("Pot of Desires", 1),
        ("Pot of Greed", 1),
        ("Return of the Dragon Lords", 1),
        ("Ring of Defense", 1),
        ("Silent Doom", 1),
        ("Silver's Cry", 1),
        ("Swing of Memories", 1),
        ("Trade-In", 1),
        ("Gift of The Mystical Elf", 1),
        ("Negate Attack", 1),
        ("Return from the Different Dimension", 1),
        ("Ring of Destruction", 1),
        ("Shadow Spell", 1),
    ],
    "World Championship 2019 Special": [
        ("Blue-Eyes White Dragon", 3),
        ("Luster Dragon #2", 1),
        ("Blue-Eyes Alternative White Dragon", 1),
        ("Chaos Emperor Dragon - Envoy of the End", 1),
        ("Deep-Eyes White Dragon", 1),
        ("Giant Germ", 1),
        ("Goddess of Sweet Revenge", 1),
        ("Kaibaman", 1),
        ("Kaiser Vorse Raider", 1),
        ("Lord of D.", 1),
        ("Neo Kaiser Glider", 1),
        ("The King of D.", 1),
        ("The White Stone of Ancients", 1),
        ("The White Stone of Legend", 1),
        ("Blue-Eyes Chaos MAX Dragon", 1),
        ("Blue-Eyes Alternative Ultimate Dragon", 1),
        ("Blue-Eyes Twin Burst Dragon", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Neo Blue-Eyes Ultimate Dragon", 1),
        ("XY-Dragon Cannon", 1),
        ("XYZ-Dragon Cannon", 1),
        ("YZ-Tank Dragon", 1),
        ("Card of Demise", 1),
        ("Cards of Consonance", 1),
        ("Chaos Form", 1),
        ("Dimension Fusion", 1),
        ("Dragon Revival Rhapsody", 1),
        ("Dragon's Mirror", 1),
        ("Forbidden Chalice", 1),
        ("Monster Reborn", 1),
        ("Pot of Extravagance", 1),
        ("Pot of Greed", 1),
        ("Return of the Dragon Lords", 1),
        ("Silver's Cry", 1),
        ("Swing of Memories", 1),
        ("Trade-In", 1),
        ("Crush Card Virus", 1),
        ("Last Turn", 1),
        ("Negate Attack", 1),
        ("Ring of Destruction", 1),
        ("Shadow Spell", 1),
    ],
    "The Eternal Duelist Soul": [
        ("Blue-Eyes White Dragon", 3),
        ("Hyozanryu", 1),
        ("Koumori Dragon", 3),
        ("Twin-Headed Fire Dragon", 2),
        ("Vorse Raider", 3),
        ("Cyber Jar", 1),
        ("Cyber-Stein", 2),
        ("Hoshiningen", 3),
        ("Nimble Momonga", 2),
        ("Sangan", 2),
        ("Sinister Serpent", 1),
        ("Witch of the Black Forest", 2),
        ("Blue-Eyes Ultimate Dragon", 3),
        ("Change of Heart", 1),
        ("Dark Hole", 1),
        ("Graceful Charity", 2),
        ("Harpie's Feather Duster", 1),
        ("Monster Reborn", 1),
        ("Mystical Space Typhoon", 1),
        ("Pot of Greed", 1),
        ("Raigeki", 1),
        ("Sebek's Blessing", 2),
        ("Snatch Steal", 1),
        ("Magic Jammer", 1),
        ("Mirror Force", 1),
        ("Solemn Judgment", 1),
    ],
    "Worldwide Edition: Stairway to the Destined Duel": [
        ("Blue-Eyes White Dragon", 3),
        ("Cyber-Tech Alligator", 2),
        ("Gadget Soldier", 2),
        ("Gemini Elf", 3),
        ("Vorse Raider", 3),
        ("Cyber-Stein", 1),
        ("Goblin Attack Force", 2),
        ("Magician of Faith", 2),
        ("Slate Warrior", 3),
        ("Blue-Eyes Ultimate Dragon", 2),
        ("Dark Hole", 1),
        ("Harpie's Feather Duster", 1),
        ("Heavy Storm", 2),
        ("Megamorph", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Premature Burial", 2),
        ("Raigeki", 1),
        ("Ring of Destruction", 2),
        ("Call of the Haunted", 1),
        ("Magic Cylinder", 1),
        ("Magic Jammer", 2),
        ("Mirror Force", 1),
        ("Negate Attack", 2),
    ],
    "The Falsebound Kingdom - Starter": [
        ("Crawling Dragon", 1),
        ("Hitotsu-Me Giant", 1),
        ("Saggi the Dark Clown", 1),
    ],
    "The Sacred Cards": [
        ("Blue-Eyes White Dragon", 3),
        ("Fairy Dragon", 3),
        ("Grappler", 3),
        ("Gyakutenno Megami", 2),
        ("Hitotsu-Me Giant", 3),
        ("Lesser Dragon", 3),
        ("Mystic Horseman", 3),
        ("Ryu-Kishin", 3),
        ("Saggi the Dark Clown", 3),
        ("Tyhone #2", 2),
        ("The Wicked Worm Beast", 3),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Kaiser Dragon", 1),
        ("Dark Energy", 1),
        ("Dragon Treasure", 1),
        ("Monster Reborn", 1),
        ("Mountain", 1),
        ("Anti Raigeki", 1),
        ("Crush Card Virus", 1),
        ("Widespread Ruin", 1),
    ],
    "World Championship 2004": [
        ("Blue-Eyes White Dragon", 3),
        ("Cyber-Tech Alligator", 2),
        ("Vorse Raider", 3),
        ("Barrel Dragon", 2),
        ("Cyber-Stein", 1),
        ("Goblin Attack Force", 3),
        ("Magician of Faith", 2),
        ("Slate Warrior", 1),
        ("Spear Dragon", 3),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Dark Hole", 1),
        ("Harpie's Feather Duster", 1),
        ("Heavy Storm", 2),
        ("Megamorph", 1),
        ("Monster Reborn", 3),
        ("Polymerization", 1),
        ("Premature Burial", 2),
        ("Raigeki", 3),
        ("Call of the Haunted", 1),
        ("Magic Cylinder", 1),
        ("Magic Jammer", 2),
        ("Mirror Force", 1),
        ("Negate Attack", 2),
        ("Ring of Destruction", 2),
        ("Torrential Tribute", 1),
    ],
    "Dawn of Destiny": [
        ("Blue-Eyes White Dragon", 3),
        ("Cyber-Tech Alligator", 3),
        ("Hitotsu-Me Giant", 1),
        ("Judge Man", 2),
        ("La Jinn the Mystical Genie of the Lamp", 1),
        ("Ryu-Kishin", 1),
        ("Saggi the Dark Clown", 1),
        ("Steel Ogre Grotto #2", 3),
        ("Swordstalker", 1),
        ("Vorse Raider", 3),
        ("Barrel Dragon", 1),
        ("The Forgiving Maiden", 3),
        ("Magician of Faith", 3),
        ("Blue-Eyes Ultimate Dragon", 3),
        ("Dark Hole", 1),
        ("Harpie's Feather Duster", 1),
        ("Heavy Storm", 1),
        ("Monster Reborn", 1),
        ("Megamorph", 1),
        ("Polymerization", 2),
        ("Premature Burial", 1),
        ("Raigeki", 1),
        ("Attack and Receive", 1),
        ("Call of the Haunted", 1),
        ("Just Desserts", 2),
        ("Magic Cylinder", 1),
        ("Magic Jammer", 1),
        ("Mirror Force", 1),
        ("Negate Attack", 1),
        ("Ring of Destruction", 1),
        ("Torrential Tribute", 1),
    ],
    "Reshef of Destruction": [
        ("Blue-Eyes White Dragon", 3),
        ("Steel Ogre Grotto #2", 1),
        ("Swordstalker", 1),
        ("Vorse Raider", 3),
        ("X-Head Cannon", 3),
        ("Ancient Lamp", 1),
        ("Blade Knight", 3),
        ("Des Feral Imp", 2),
        ("Invitation to a Dark Sleep", 1),
        ("Lord of D.", 1),
        ("Obelisk the Tormentor", 1),
        ("Y-Dragon Head", 3),
        ("Z-Metal Tank", 3),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("XY-Dragon Cannon", 1),
        ("XYZ-Dragon Cannon", 1),
        ("XZ-Tank Cannon", 1),
        ("YZ-Tank Dragon", 1),
        ("Dark Energy", 3),
        ("Heavy Storm", 1),
        ("Megamorph", 3),
        ("Swords of Revealing Light", 2),
        ("Crush Card Virus", 2),
        ("Shadow Spell", 2),
    ],
    "Reshef of Destruction (2)": [
        ("Blue-Eyes White Dragon", 3),
        ("Vorse Raider", 3),
        ("X-Head Cannon", 3),
        ("Ancient Lamp", 3),
        ("Des Volstgalph", 1),
        ("Lord of D.", 1),
        ("Obelisk the Tormentor", 1),
        ("Y-Dragon Head", 3),
        ("Z-Metal Tank", 3),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Dragon Master Knight", 1),
        ("XY-Dragon Cannon", 1),
        ("XYZ-Dragon Cannon", 1),
        ("XZ-Tank Cannon", 1),
        ("YZ-Tank Dragon", 1),
        ("Change of Heart", 3),
        ("Harpie's Feather Duster", 3),
        ("Megamorph", 3),
        ("Monster Reborn", 3),
        ("Pot of Greed", 3),
        ("Swords of Revealing Light", 3),
        ("Torrential Tribute", 3),
    ],
    "7 Trials to Glory: Standard": [
        ("Archfiend Soldier", 3),
        ("Blue-Eyes White Dragon", 3),
        ("Cyber-Tech Alligator", 3),
        ("Luster Dragon #2", 3),
        ("Vorse Raider", 3),
        ("Black Luster Soldier - Envoy of the Beginning", 1),
        ("Chaos Emperor Dragon - Envoy of the End", 1),
        ("Cyber-Stein", 2),
        ("Goblin Attack Force", 3),
        ("Hane-Hane", 1),
        ("Man-Eater Bug", 1),
        ("Magician of Faith", 2),
        ("Penguin Soldier", 1),
        ("Soul of Purity and Light", 3),
        ("Spear Dragon", 3),
        ("Blue-Eyes Ultimate Dragon", 2),
        ("Big Bang Shot", 3),
        ("Graceful Charity", 1),
        ("Monster Reborn", 1),
        ("Mage Power", 1),
        ("Change of Heart", 1),
        ("Heavy Storm", 1),
        ("United We Stand", 1),
        ("Polymerization", 1),
        ("Card Destruction", 1),
        ("Magic Jammer", 2),
        ("Negate Attack", 3),
        ("Seven Tools of the Bandit", 1),
        ("Trap Hole", 1),
        ("Call of the Haunted", 1),
    ],
    "7 Trials to Glory: Advanced": [
        ("Archfiend Soldier", 3),
        ("Beast of Talwar", 1),
        ("Blue-Eyes White Dragon", 3),
        ("Cyber-Tech Alligator", 3),
        ("Luster Dragon #2", 3),
        ("Mad Dog of Darkness", 3),
        ("Vorse Raider", 3),
        ("Cyber-Stein", 1),
        ("Giant Germ", 3),
        ("Goblin Attack Force", 3),
        ("Hane-Hane", 1),
        ("Jinzo", 1),
        ("Nimble Momonga", 3),
        ("Slate Warrior", 1),
        ("Spear Dragon", 3),
        ("Blue-Eyes Ultimate Dragon", 2),
        ("Big Bang Shot", 3),
        ("Card Destruction", 1),
        ("Dark Hole", 1),
        ("Graceful Charity", 1),
        ("Heavy Storm", 1),
        ("Polymerization", 1),
        ("Call of the Haunted", 1),
        ("Enchanted Javelin", 3),
        ("Magic Cylinder", 1),
        ("Mirror Force", 1),
        ("Negate Attack", 3),
        ("Ring of Destruction", 1),
        ("Torrential Tribute", 1),
        ("Trap Hole", 3),
        ("Widespread Ruin", 3),
    ],
    "X-Y-Z": [
        ("Cyber-Tech Alligator", 1),
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Ryu-Kishin Powered", 1),
        ("X-Head Cannon", 3),
        ("Ancient Lamp", 2),
        ("Maha Vailo", 1),
        ("Shining Angel", 2),
        ("The Wicked Worm Beast", 3),
        ("Y-Dragon Head", 3),
        ("Z-Metal Tank", 3),
        ("XY-Dragon Cannon", 2),
        ("XYZ-Dragon Cannon", 3),
        ("XZ-Tank Cannon", 2),
        ("YZ-Tank Dragon", 2),
        ("Shrink", 2),
        ("Combination Attack", 2),
        ("Enemy Controller", 2),
        ("Frontline Base", 1),
        ("Luminous Spark", 2),
        ("Machine Conversion Factory", 1),
        ("Premature Burial", 1),
        ("Silent Doom", 1),
        ("Destruction Ring", 2),
        ("Dust Tornado", 1),
        ("Formation Union", 2),
        ("Negate Attack", 2),
        ("Ring of Destruction", 1),
    ],
    "Blue-Eyes Burst": [
        ("Blue-Eyes White Dragon", 3),
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Vorse Raider", 3),
        ("Ancient Lamp", 2),
        ("D.D. Warrior Lady", 1),
        ("Gear Golem the Moving Fortress", 1),
        ("Gilasaurus", 2),
        ("Sangan", 1),
        ("Sinister Serpent", 1),
        ("Slate Warrior", 2),
        ("Spirit Reaper", 2),
        ("Versago the Destroyer", 2),
        ("Blue-Eyes Ultimate Dragon", 3),
        ("Cost Down", 2),
        ("De-Fusion", 1),
        ("Fiend's Sanctuary", 1),
        ("Fusion Gate", 1),
        ("Graceful Charity", 1),
        ("Mystical Space Typhoon", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Raigeki", 1),
        ("Snatch Steal", 1),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Mirror Force", 1),
        ("Ring of Destruction", 1),
        ("Soul Resurrection", 1),
        ("Trap Jammer", 1),
    ],
    "Fist of Fury": [
        ("Cyber-Tech Alligator", 2),
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Vorse Raider", 3),
        ("X-Head Cannon", 2),
        ("Ancient Lamp", 2),
        ("Cyber Jar", 1),
        ("Enraged Battle Ox", 2),
        ("Gilasaurus", 3),
        ("Obelisk the Tormentor", 1),
        ("Sangan", 1),
        ("Spirit Reaper", 3),
        ("Brain Control", 1),
        ("Graceful Charity", 1),
        ("Monster Reincarnation", 1),
        ("Mystical Space Typhoon", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Silent Doom", 1),
        ("Soul Exchange", 3),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Dark Mirror Force", 1),
        ("Dust Tornado", 1),
        ("Interdimensional Matter Transporter", 1),
        ("Ring of Destruction", 1),
        ("Soul Resurrection", 1),
        ("Trap Jammer", 1),
    ],
    "Kaiser Impact": [
        ("Blue-Eyes White Dragon", 2),
        ("Vorse Raider", 2),
        ("X-Head Cannon", 2),
        ("Ancient Lamp", 1),
        ("Chaos Emperor Dragon - Envoy of the End", 1),
        ("Copycat", 2),
        ("D.D. Warrior Lady", 1),
        ("Gilasaurus", 1),
        ("Kycoo the Ghost Destroyer", 2),
        ("Magician of Faith", 1),
        ("Reflect Bounder", 1),
        ("Sangan", 1),
        ("Sinister Serpent", 1),
        ("Spirit Reaper", 2),
        ("Cost Down", 1),
        ("Different Dimension Capsule", 2),
        ("Graceful Charity", 1),
        ("Heavy Storm", 1),
        ("Lightning Vortex", 1),
        ("Mystical Space Typhoon", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Snatch Steal", 1),
        ("Upstart Goblin", 2),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Dust Tornado", 1),
        ("Mirror Force", 1),
        ("Raigeki Break", 1),
        ("Ring of Destruction", 1),
        ("Sakuretsu Armor", 1),
        ("Trap Jammer", 1),
    ],
    "Obelisk Impact": [
        ("Cyber-Tech Alligator", 2),
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Vorse Raider", 3),
        ("X-Head Cannon", 2),
        ("Ancient Lamp", 2),
        ("Cyber Jar", 1),
        ("Enraged Battle Ox", 2),
        ("Gilasaurus", 3),
        ("Obelisk the Tormentor", 1),
        ("Sangan", 1),
        ("Spirit Reaper", 3),
        ("Brain Control", 1),
        ("Graceful Charity", 1),
        ("Monster Reincarnation", 1),
        ("Mystical Space Typhoon", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Silent Doom", 1),
        ("Soul Exchange", 3),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Dark Mirror Force", 1),
        ("Dust Tornado", 1),
        ("Interdimensional Matter Transporter", 1),
        ("Ring of Destruction", 1),
        ("Soul Resurrection", 1),
        ("Trap Jammer", 1),
    ],
    "Jump Ultimate Stars": [
        ("Blue-Eyes White Dragon", 1),
        ("Crush Card Virus", 1),
    ],
    "World Championship 2007": [
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Vorse Raider", 3),
        ("D.D. Assailant", 1),
        ("D.D. Warrior Lady", 1),
        ("Giant Germ", 3),
        ("Gilasaurus", 1),
        ("Gravekeeper's Spy", 1),
        ("Magician of Faith", 1),
        ("Mask of Darkness", 1),
        ("Obelisk the Tormentor", 1),
        ("Sangan", 1),
        ("Spirit Reaper", 1),
        ("Wall of Illusion", 2),
        ("Brain Control", 2),
        ("Giant Trunade", 1),
        ("Graceful Charity", 1),
        ("Heavy Storm", 1),
        ("Mystic Plasma Zone", 1),
        ("Mystical Space Typhoon", 1),
        ("Nobleman of Crossout", 1),
        ("Premature Burial", 1),
        ("Scapegoat", 1),
        ("Gold Sarcophagus", 3),
        ("Shield Crush", 1),
        ("Stray Lambs", 1),
        ("Swords of Revealing Light", 1),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Mirror Force", 1),
        ("Ring of Destruction", 1),
        ("Ultimate Offering", 1),
    ],
    "World Championship Tournament 2007 (2)": [
        ("Blue-Eyes White Dragon", 3),
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Vorse Raider", 3),
        ("Ancient Lamp", 1),
        ("Giant Germ", 3),
        ("Kaiser Sea Horse", 2),
        ("King of the Swamp", 2),
        ("Mask of Darkness", 1),
        ("The Dark - Hex-Sealed Fusion", 1),
        ("Sangan", 1),
        ("Spirit Reaper", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Ancient Rules", 1),
        ("Brain Control", 1),
        ("Burst Stream of Destruction", 1),
        ("Dragon's Mirror", 1),
        ("Enemy Controller", 1),
        ("Fiend's Sanctuary", 1),
        ("Heavy Storm", 1),
        ("Lightning Vortex", 2),
        ("Mystical Space Typhoon", 1),
        ("Polymerization", 2),
        ("Smashing Ground", 1),
        ("Birthright", 2),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Mirror Force", 1),
        ("Raigeki Break", 1),
        ("Ring of Destruction", 1),
    ],
    "Ruinous Beast": [
        ("Blue-Eyes White Dragon", 3),
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Vorse Raider", 3),
        ("Ancient Lamp", 1),
        ("Giant Germ", 3),
        ("Kaiser Sea Horse", 3),
        ("Mask of Darkness", 2),
        ("Sangan", 1),
        ("Spirit Reaper", 1),
        ("The Light - Hex-Sealed Fusion", 2),
        ("Blue-Eyes Ultimate Dragon", 3),
        ("Brain Control", 1),
        ("Burst Stream of Destruction", 2),
        ("Dragon's Mirror", 1),
        ("Enemy Controller", 2),
        ("Heavy Storm", 1),
        ("Mystical Space Typhoon", 1),
        ("Premature Burial", 1),
        ("Smashing Ground", 1),
        ("Polymerization", 2),
        ("Birthright", 2),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Dust Tornado", 2),
        ("Mirror Force", 1),
        ("Sakuretsu Armor", 2),
    ],
    "Noble Soul": [
        ("Blue-Eyes White Dragon", 3),
        ("La Jinn the Mystical Genie of the Lamp", 2),
        ("Vorse Raider", 3),
        ("Ancient Lamp", 1),
        ("Giant Germ", 3),
        ("Kaiser Sea Horse", 2),
        ("King of the Swamp", 2),
        ("Mask of Darkness", 1),
        ("Sangan", 1),
        ("Spirit Reaper", 1),
        ("The Dark - Hex-Sealed Fusion", 1),
        ("Blue-Eyes Ultimate Dragon", 3),
        ("Ancient Rules", 1),
        ("Brain Control", 1),
        ("Burst Stream of Destruction", 1),
        ("Dragon's Mirror", 1),
        ("Enemy Controller", 1),
        ("Fiend's Sanctuary", 1),
        ("Heavy Storm", 1),
        ("Lightning Vortex", 2),
        ("Mystical Space Typhoon", 1),
        ("Polymerization", 2),
        ("Smashing Ground", 1),
        ("Birthright", 2),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Mirror Force", 1),
        ("Raigeki Break", 1),
        ("Widespread Ruin", 1),
    ],
    "Online Duel Accelerator": [
        ("Blue-Eyes White Dragon", 3),
        ("Divine Dragon Ragnarok", 3),
        ("Axe Dragonute", 2),
        ("Fusilier Dragon, the Dual-Mode Beast", 2),
        ("Lancer Dragonute", 2),
        ("Masked Dragon", 3),
        ("Sangan", 1),
        ("The Dark - Hex-Sealed Fusion", 2),
        ("White-Horned Dragon", 2),
        ("Blue-Eyes Ultimate Dragon", 3),
        ("Five-Headed Dragon", 3),
        ("Creature Swap", 1),
        ("Dragon's Mirror", 2),
        ("Future Fusion", 1),
        ("Mystical Space Typhoon", 1),
        ("Snatch Steal", 1),
        ("Stamping Destruction", 2),
        ("Birthright", 1),
        ("Call of the Haunted", 1),
        ("Crush Card Virus", 1),
        ("Ring of Destruction", 1),
    ],
    "Pulse of Trishula": [
        ("Blue-Eyes White Dragon", 3),
        ("Kaibaman", 1),
        ("King of the Swamp", 1),
        ("Blue-Eyes Ultimate Dragon", 1),
        ("Burst Stream of Destruction", 1),
        ("Polymerization", 1),
        ("Birthright", 1),
    ],
}