LEON_DECK = {
    "Fairy Tale": [
        ("Tom Thumb [A]", 1),
        ("Prinzessin", 1),
        ("Forest Hunter [A]", 1),
        ("Forest Wolf [A]", 2),
        ("Glife the Phantom Bird", 2),
        ("Globerman [A]", 1),
        ("Hexe Trude", 1),
        ("Iron Hans", 1),
        ("Iron Knight", 3),
        ("Little Red Riding Hood [A]", 1),
        ("Pumpkin Carriage", 2),
        ("Seven Kid Goats [A]", 1),
        ("Thorn Princess [A]", 1),
        ("100-Year Awakening [A]", 1),
        ("Curse of Thorns [A]", 1),
        ("Giant's Training [A]", 1),
        ("Gingerbread House", 1),
        ("Glass Slippers", 1),
        ("Gold Moon Coin", 1),
        ("Golden Castle of Stromberg", 1),
        ("Iron Cage", 1),
        ("Monster Reborn", 1),
        ("Mystical Space Typhoon", 1),
        ("Negate Attack", 1),
        ("Pot of Greed", 1),
        ("Spinning Wheel Spindle [A]", 1),
        ("Water of Life", 1),
        ("Mirror Force", 1)
    ],
}