PEGASUS_DECKS = {
    "Manga": [
        ("Bickuribox", 1),
        ("Dark Rabbit", 1),
        ("Illusionist Faceless Mage", 1),
        ("Wattkid", 1),
        ("Parrot Dragon", 1),
        ("Red Archery Girl", 1),
        ("Rogue Doll", 1),
        ("Ryu-Ran", 1),
        ("Toon Alligator", 1),
        ("Thousand-Eyes Idol", 1),
        ("Dark-Eyes Illusionist", 1),
        ("Dragon Capture Jar", 1),
        ("Dragon Piper", 1),
        ("Jigen Bakudan", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Manga Ryu-Ran", 1),
        ("Toon Mermaid", 1),
        ("Toon Summoned Skull", 1),
        ("Relinquished", 1),
        ("Thousand-Eyes Restrict", 1),
        ("Black Illusion Ritual", 1),
        ("Mimicat", 1),
        ("Eye of Illusion", 1),
        ("Magic Neutralizing Force [M]", 1),
        ("Negative Energy [M]", 1),
        ("Polymerization", 1),
        ("Shine Palace", 1),
        ("Toon World", 1),
        ("Gorgon's Eye", 1),
        ("Mermaid's Tear [M]", 1),
        ("Prophecy [M]", 1),
        ("Trap Displacement [M]", 1),
    ],
    "Duelist Kingdom": [
        ("Bickuribox", 1),
        ("Dark Rabbit", 1),
        ("Flying Elephant", 1),
        ("Illusionist Faceless Mage", 1),
        ("Killer Needle", 1),
        ("Parrot Dragon", 1),
        ("Red Archery Girl", 1),
        ("Ryu-Ran", 1),
        ("Toon Alligator", 1),
        ("Thousand-Eyes Idol", 1),
        ("Dark-Eyes Illusionist", 1),
        ("Dragon Capture Jar", 1),
        ("Dragon Piper", 1),
        ("Jigen Bakudan", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Manga Ryu-Ran", 1),
        ("Toon Mermaid", 1),
        ("Toon Summoned Skull", 1),
        ("Relinquished", 1),
        ("Thousand-Eyes Restrict", 1),
        ("Black Illusion Ritual", 1),
        ("Mimicat", 1),
        ("Eye of Illusion", 1),
        ("Magical Neutralizing Force Field [A]", 1),
        ("Negative Energy [A]", 1),
        ("Polymerization", 1),
        ("Shine Palace", 1),
        ("Toon World", 1),
        ("Gorgon's Eye", 1),
        ("Prophecy [A]", 1),
        ("Sun Shower [A]", 1),
        ("Tears of a Mermaid [A]", 1),
        ("Trap Displacement [A]", 1),
    ],
    "Waking the Dragons": [
        ("Toon Alligator", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Dark Magician Girl", 1),
        ("Toon Masked Sorcerer", 1),
        ("Thousand-Eyes Restrict", 1),
        ("Toon Rollback", 1),
        ("Toon Table of Contents", 1),
        ("Toon World", 1),
        ("Toon Mask", 1),
    ],
    "Pyramid of Light": [
        ("Thousand-Eyes Idol", 1),
        ("Toon Alligator", 1),
        ("Manju of the Ten Thousand Hands", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Manga Ryu-Ran", 2),
        ("Toon Cannon Soldier", 1),
        ("Toon Dark Magician Girl", 1),
        ("Toon Gemini Elf", 3),
        ("Toon Goblin Attack Force", 3),
        ("Toon Masked Sorcerer", 2),
        ("Toon Mermaid", 1),
        ("Toon Summoned Skull", 1),
        ("Relinquished", 1),
        ("Thousand-Eyes Restrict", 1),
        ("Black Illusion Ritual", 1),
        ("Shine Palace", 1),
        ("Card of Sanctity", 1),
        ("Cost Down", 1),
        ("Fissure", 1),
        ("Heavy Storm", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Snatch Steal", 1),
        ("Toon Table of Contents", 3),
        ("Toon World", 2),
        ("Jar of Greed", 2),
        ("Solemn Judgment", 1),
        ("Toon Defense", 1),
        ("Ultimate Offering", 1),
    ],
    "GX": [
        ("Toon Alligator", 1),
        ("Toon Dark Magician Girl", 1),
        ("Toon Ancient Gear Golem", 1),
        ("Comic Hand", 1),
        ("Mimicat", 1),
        ("Shadow Toon", 1),
        ("Toon Kingdom", 1),
        ("Gorgon's Eye", 1),
        ("Toon Briefcase", 1),
    ],
    "Championship Series Providence 2012": [
        ("Dark Rabbit", 1),
        ("Gemini Elf", 1),
        ("Red Archery Girl", 1),
        ("Thousand-Eyes Idol", 1),
        ("Cannon Soldier", 1),
        ("Dragon Capture Jar", 1),
        ("Dragon Piper", 1),
        ("Jigen Bakudan", 1),
        ("Toon Cannon Soldier", 1),
        ("Toon Gemini Elf", 1),
        ("Toon Goblin Attack Force", 1),
        ("Toon Masked Sorcerer", 1),
        ("Toon Mermaid", 1),
        ("Toon Summoned Skull", 1),
        ("Relinquished", 1),
        ("Thousand-Eyes Restrict", 1),
        ("Black Illusion Ritual", 1),
        ("Heavy Storm", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Pot of Greed", 1),
        ("Snatch Steal", 1),
        ("Toon World", 1),
        ("Solemn Judgment", 1),
    ],
    "North American World Championship Qualifiers 2013 Special": [
        ("Gorz the Emissary of Darkness", 1),
        ("Wind-Up Dog", 1),
        ("Wind-Up Magician", 1),
        ("Wind-Up Rabbit", 3),
        ("Wind-Up Rat", 2),
        ("Wind-Up Shark", 2),
        ("Wind-Up Warrior", 2),
        ("Adreus, Keeper of Armageddon", 1),
        ("Tiras, Keeper of Genesis", 1),
        ("Wind-Up Zenmaines", 1),
        ("Book of Moon", 1),
        ("Dark Hole", 1),
        ("Pot of Duality", 1),
        ("Smashing Ground", 1),
        ("Wind-Up Factory", 1),
        ("Bottomless Trap Hole", 1),
        ("Compulsory Evacuation Device", 1),
        ("Dimensional Prison", 2),
        ("Mirror Force", 2),
    ],
    "North American World Championship Qualifiers 2015 Special": [
        ("Toon Alligator", 1),
        ("Toon Cyber Dragon", 1),
        ("Toon Masked Sorcerer", 1),
        ("Toon Mermaid", 1),
        ("Toon Goblin Attack Force", 1),
        ("Toon Kingdom", 2),
        ("Pot of Greed", 1),
        ("Shard of Greed", 1),
        ("Shadow Toon", 1),
        ("Heavy Storm", 1),
        ("Monster Reborn", 1),
        ("Mimicat", 1),
        ("Comic Hand", 1),
        ("Toon Briefcase", 1),
        ("Toon Mask", 1),
    ],
    "YCS Origins 2016 Special": [
        ("Tour Guide From the Underworld", 1),
        ("Graff, Malebranche of the Burning Abyss", 1),
        ("Scarm, Malebranche of the Burning Abyss", 1),
        ("Calcab, Malebranche of the Burning Abyss", 1),
        ("Barbar, Malebranche of the Burning Abyss", 1),
        ("Draghig, Malebranche of the Burning Abyss", 1),
        ("Farfa, Malebranche of the Burning Abyss", 3),
        ("Alich, Malebranche of the Burning Abyss", 1),
        ("Libic, Malebranche of the Burning Abyss", 1),
        ("Cir, Malebranche of the Burning Abyss", 2),
        ("Maxx \"C\"", 1),
        ("Crane Crane", 1),
        ("Rubic, Malebranche of the Burning Abyss", 1),
        ("Malacoda, Netherlord of the Burning Abyss", 1),
        ("Thousand-Eyes Restrict", 1),
        ("Dante, Pilgrim of the Burning Abyss", 1),
        ("Dante, Traveler of the Burning Abyss", 3),
        ("Beatrice, Lady of the Eternal", 1),
        ("Good & Evil in the Burning Abyss", 1),
        ("Instant Fusion", 1),
        ("Dark Hole", 1),
        ("The Traveler and the Burning Abyss", 2),
        ("Fire Lake of the Burning Abyss", 2),
    ],
    "North American World Championship Qualifiers 2017 Special": [
        ("Blue-Eyes Toon Dragon", 1),
        ("Red-Eyes Toon Dragon", 1),
        ("Toon Barrel Dragon", 1),
        ("Toon Dark Magician", 1),
        ("Comic Hand", 1),
        ("Graceful Charity", 1),
        ("Mimicat", 1),
        ("Monster Reborn", 1),
        ("Pot of Greed", 1),
        ("Toon Kingdom", 1),
        ("Judgment of Anubis", 1),
    ],
    "Live-action Speed Duel 2020": [
        ("Illusionist Faceless Mage", 1),
        ("Thousand-Eyes Idol", 1),
        ("Sonic Bird", 1),
        ("Toon Dark Magician", 1),
        ("Toon Gemini Elf", 1),
        ("Toon Mermaid", 1),
        ("Toon Summoned Skull", 1),
        ("Relinquished", 1),
        ("Thousand-Eyes Restrict", 1),
        ("Black Illusion Ritual", 1),
        ("Toon World", 1),
        ("Security Orb", 1),
        ("Toon Mask", 1),
    ],
    "The Eternal Duelist Soul": [
        ("Dark-Eyes Illusionist", 2),
        ("Red Archery Girl", 3),
        ("Rogue Doll", 2),
        ("Vorse Raider", 3),
        ("Cyber Jar", 1),
        ("Nimble Momonga", 3),
        ("Sinister Serpent", 1),
        ("Witch of the Black Forest", 2),
        ("Blue-Eyes Toon Dragon", 1),
        ("Manga Ryu-Ran", 1),
        ("Toon Summoned Skull", 3),
        ("Relinquished", 2),
        ("Black Illusion Ritual", 2),
        ("Change of Heart", 1),
        ("Dark Hole", 1),
        ("Graceful Charity", 1),
        ("Harpie's Feather Duster", 1),
        ("Megamorph", 1),
        ("Monster Reborn", 1),
        ("Pot of Greed", 1),
        ("Raigeki", 1),
        ("Swords of Revealing Light", 1),
        ("Toon World", 2),
        ("Magic Jammer", 1),
        ("Mirror Force", 1),
        ("Solemn Judgment", 1),
        ("Time Machine", 1),
    ],
    "Worldwide Edition: Stairway to the Destined Duel": [
        ("Thousand-Eyes Idol", 3),
        ("Nimble Momonga", 1),
        ("Sinister Serpent", 1),
        ("Slate Warrior", 2),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Mermaid", 3),
        ("Toon Summoned Skull", 3),
        ("Relinquished", 3),
        ("Thousand-Eyes Restrict", 1),
        ("Black Illusion Ritual", 3),
        ("Change of Heart", 1),
        ("Dark Hole", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 1),
        ("Premature Burial", 2),
        ("Raigeki", 1),
        ("Snatch Steal", 1),
        ("Swords of Revealing Light", 1),
        ("Toon World", 3),
        ("Ring of Destruction", 1),
        ("Enchanted Javelin", 3),
        ("Magic Cylinder", 1),
        ("Mirror Force", 1),
        ("Mirror Wall", 1),
        ("Numinous Healer", 3),
    ],
    "Toonized": [
        ("Summoned Skull", 2),
        ("Thousand-Eyes Idol", 1),
        ("Vorse Raider", 3),
        ("Cyber Jar", 1),
        ("Morphing Jar", 1),
        ("Nimble Momonga", 3),
        ("Sinister Serpent", 1),
        ("Slate Warrior", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Mermaid", 3),
        ("Toon Summoned Skull", 2),
        ("Relinquished", 2),
        ("Black Illusion Ritual", 2),
        ("Change of Heart", 1),
        ("Dark Hole", 1),
        ("Monster Reborn", 1),
        ("Premature Burial", 1),
        ("Raigeki", 1),
        ("Snatch Steal", 1),
        ("Swords of Revealing Light", 1),
        ("Toon World", 2),
        ("Enchanted Javelin", 2),
        ("Magic Cylinder", 1),
        ("Mirror Force", 1),
        ("Mirror Wall", 1),
        ("Numinous Healer", 2),
        ("Ring of Destruction", 1),
    ],
    "The Dawn of Destiny": [
        ("Aqua Madoor", 2),
        ("Parrot Dragon", 1),
        ("Red Archery Girl", 1),
        ("Rogue Doll", 1),
        ("Ryu-Ran", 1),
        ("Thousand-Eyes Idol", 2),
        ("Vorse Raider", 2),
        ("Cyber Jar", 1),
        ("Morphing Jar", 1),
        ("Sinister Serpent", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Mermaid", 2),
        ("Toon Summoned Skull", 2),
        ("Relinquished", 2),
        ("Thousand-Eyes Restrict", 1),
        ("Black Illusion Ritual", 2),
        ("Change of Heart", 1),
        ("Dark Hole", 1),
        ("Megamorph", 1),
        ("Monster Reborn", 1),
        ("Polymerization", 2),
        ("Premature Burial", 1),
        ("Raigeki", 1),
        ("Snatch Steal", 1),
        ("Toon World", 2),
        ("Life Absorbing Machine", 2),
        ("Magic Cylinder", 1),
        ("Mirror Wall", 1),
        ("Numinous Healer", 2),
        ("Ring of Destruction", 1),
        ("Solemn Wishes", 2),
    ],
    "Reshef of Destruction": [
        ("Big Shield Gardna", 3),
        ("Castle of Dark Illusions", 3),
        ("Blue-Eyes Toon Dragon", 3),
        ("Toon Summoned Skull", 3),
        ("Relinquished", 3),
        ("Thousand-Eyes Restrict", 3),
        ("Change of Heart", 3),
        ("Harpie's Feather Duster", 3),
        ("Megamorph", 3),
        ("Monster Reborn", 3),
        ("Pot of Greed", 3),
        ("Swords of Revealing Light", 3),
        ("Torrential Tribute", 3),
    ],
    "Toon World!": [
        ("Dark Rabbit", 2),
        ("Parrot Dragon", 1),
        ("Thousand-Eyes Idol", 1),
        ("Toon Alligator", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Cannon Soldier", 2),
        ("Toon Dark Magician Girl", 1),
        ("Toon Gemini Elf", 2),
        ("Toon Goblin Attack Force", 1),
        ("Toon Masked Sorcerer", 1),
        ("Toon Mermaid", 2),
        ("Toon Summoned Skull", 2),
        ("Relinquished", 2),
        ("Thousand-Eyes Restrict", 3),
        ("Black Illusion Ritual", 2),
        ("Emergency Provisions", 1),
        ("Fusion Gate", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Scapegoat", 2),
        ("Toon Table of Contents", 3),
        ("Toon World", 3),
        ("Call of the Haunted", 1),
        ("Magic Jammer", 1),
        ("Royal Decree", 1),
        ("Solemn Wishes", 1),
        ("Toon Defense", 1),
        ("Ultimate Offering", 2),
    ],
    "Toon Channel": [
        ("Thousand-Eyes Idol", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Cannon Soldier", 3),
        ("Toon Dark Magician Girl", 2),
        ("Toon Gemini Elf", 3),
        ("Toon Goblin Attack Force", 3),
        ("Toon Masked Sorcerer", 3),
        ("Toon Summoned Skull", 1),
        ("Relinquished", 2),
        ("Thousand-Eyes Restrict", 3),
        ("Black Illusion Ritual", 2),
        ("Emergency Provisions", 1),
        ("Fusion Gate", 1),
        ("Monster Reborn", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Scapegoat", 2),
        ("Toon Table of Contents", 3),
        ("Toon World", 3),
        ("Call of the Haunted", 1),
        ("Magic Jammer", 1),
        ("Royal Decree", 1),
        ("Toon Defense", 1),
        ("Ultimate Offering", 2),
    ],
    "Toon Doom": [
        ("Thousand-Eyes Idol", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Cannon Soldier", 2),
        ("Toon Dark Magician Girl", 2),
        ("Toon Gemini Elf", 3),
        ("Toon Goblin Attack Force", 2),
        ("Toon Masked Sorcerer", 2),
        ("Toon Mermaid", 2),
        ("Toon Summoned Skull", 2),
        ("Relinquished", 2),
        ("Thousand-Eyes Restrict", 3),
        ("Black Illusion Ritual", 2),
        ("Emergency Provisions", 1),
        ("Fusion Gate", 1),
        ("Pot of Greed", 1),
        ("Premature Burial", 1),
        ("Scapegoat", 2),
        ("Toon Table of Contents", 3),
        ("Toon World", 3),
        ("Call of the Haunted", 1),
        ("Magic Jammer", 1),
        ("Royal Decree", 1),
        ("Solemn Wishes", 1),
        ("Toon Defense", 1),
        ("Ultimate Offering", 2),
    ],
    "Future Vision": [
        ("Dandylion", 1),
        ("Spirit Reaper", 1),
        ("Blue-Eyes Toon Dragon", 1),
        ("Toon Cannon Soldier", 3),
        ("Toon Dark Magician Girl", 2),
        ("Toon Gemini Elf", 3),
        ("Toon Goblin Attack Force", 3),
        ("Toon Masked Sorcerer", 3),
        ("Toon Summoned Skull", 1),
        ("Big Bang Shot", 2),
        ("Fiend's Sanctuary", 1),
        ("Fissure", 1),
        ("Premature Burial", 1),
        ("Scapegoat", 1),
        ("Shrink", 2),
        ("Smashing Ground", 1),
        ("Toon Table of Contents", 3),
        ("Toon World", 3),
        ("Bottomless Trap Hole", 1),
        ("Call of the Haunted", 1),
        ("Dimensional Prison", 1),
        ("Mirror Force", 1),
        ("Sakuretsu Armor", 1),
        ("Toon Defense", 1),
        ("Ultimate Offering", 1),
    ],
    "Illusionist Faceless Mage": [
        ("Dark Rabbit", 1),
        ("Parrot Dragon", 1),
        ("Saggi the Dark Clown", 1),
        ("Stuffed Animal", 1),
        ("Flame Swordsman", 1),
        ("Genin", 1),
        ("Illusionist Faceless Mage", 1),
        ("Magical Neutralizing Force Field [G]", 1),
        ("Toon World", 1),
    ],
    "Monster Army": [
        ("Dark Rabbit", 1),
        ("Parrot Dragon", 1),
        ("Bickuribox", 1),
    ],
    "Imperfect Paradise": [
        ("Lucky Trinket", 1),
        ("Rogue Doll", 1),
        ("Ancient Tree of Enlightenment", 1),
        ("Green Phantom King", 1),
        ("Haniwa", 1),
        ("Penguin Soldier", 1),
    ],
    "Shrine of Chaos #1": [
        ("Carat Idol [G]", 1),
        ("Lucky Trinket", 1),
        ("Magician of Faith", 1),
        ("Rogue Doll", 1),
        ("Jigen Bakudan", 1),
        ("Parrot Dragon", 1),
        ("Larvas", 1),
        ("Rock Ogre Grotto #1", 1),
        ("Torike", 1),
    ],
    "Shrine of Chaos #2": [
        ("Parrot Dragon", 1),
        ("Carat Idol [G]", 1),
        ("Lucky Trinket", 1),
        ("Magician of Faith", 1),
        ("Jellyfish", 1),
        ("White Dolphin", 1),
        ("Arsenal Bug", 1),
        ("Wattkid", 2),
        ("Illusionist Faceless Mage", 1),
    ],
    "Gem-Knights": [
        ("Gem-Knight Alexandrite", 1),
        ("Gem-Knight Crystal", 1),
        ("Gem-Knight Prismaura", 1),
        ("Gem-Knight Topaz", 1),
        ("Dark Factory of Mass Production", 1),
        ("Gem-Knight Fusion", 1),
    ],
}