#TODO: Finish Yugi, Start Kaiba and Joey

DECKS_DATA = {
    "Yugi Muto": {
        "Toei - First Series": [
            ("Big Tree [A]", 1),
            ("Black Scorpion [A]", 1),
            ("Blackland Fire Dragon", 1),
            ("Chimera [A]", 1),
            ("Dark Mammoth [A]", 1),
            ("Death Wolf [A]", 1),
            ("Ghost [A]", 1),
            ("Iron Beetle [A]", 1),
            ("King Rex [A]", 1),
            ("Koumori Dragon", 1),
            ("Mushroom Man", 1),
            ("Mystical Elf", 1),
            ("Neon Knight [A]", 1),
            ("Night Soldier [A]", 1),
            ("Rock-Gun [A]", 1),
            ("Shadowman [A]", 1),
            ("Skull Servant", 1),
            ("Sleeping Worm [A]", 1),
            ("Summoned Skull", 1),
            ("Violet Hecate [A]", 1),
            ("Clock Card [A]", 1),
            ("Magical Hats", 1),
            ("Flute of Light [A]", 1),
            ("Miraculous Water [A]", 1),
            ("Monster Reborn", 1),
        ],
        "Toei - Death-T": [
            ("Chimera [A]", 1),
            ("Exodia the Forbidden One", 1),
            ("Gaia The Fierce Knight", 1),
            ("Gremlin [A]", 1),
            ("Koumori Dragon", 1),
            ("Left Arm of the Forbidden One", 1),
            ("Left Leg of the Forbidden One", 1),
            ("Mammoth Graveyard", 1),
            ("Right Arm of the Forbidden One", 1),
            ("Right Leg of the Forbidden One", 1),
            ("Winged Dragon, Guardian of the Fortress #1", 1),
            ("Swords of Revealing Light", 1),
        ],
        "Toei - Movie": [
            ("Beaver Warrior", 1),
            ("Celtic Guardian", 1),
            ("Curse of Dragon", 1),
            ("Dark Magician", 1),
            ("Feral Imp", 1),
            ("Gaia The Fierce Knight", 1),
            ("Hitotsu-Me Giant", 1),
            ("Meteor B. Dragon [A]", 1),
            ("Meteor Dragon (Toei) [B]", 1),
            ("Red-Eyes B. Dragon [B]", 1),
            ("Summoned Skull", 1),
            ("Dragonic Pulse of the Land [A]", 1),
            ("Magical Hats", 1),
            ("Polymerization", 1),
            ("Curse of Dark Cross Star [A]", 1),
        ],
        "Duelist Kingdom": [
            ("Battle Steer", 1),
            ("Beaver Warrior", 1),
            ("Celtic Guardian", 1),
            ("Curse of Dragon", 1),
            ("Dark Magician", 1),
            ("Feral Imp", 1),
            ("Gaia The Fierce Knight", 1),
            ("Giant Soldier of Stone", 1),
            ("Griffore", 1),
            ("Horn Imp", 1),
            ("Koumori Dragon", 1),
            ("Left Arm of the Forbidden One", 1),
            ("Left Leg of the Forbidden One", 1),
            ("Mammoth Graveyard", 1),
            ("Mystical Elf", 1),
            ("Right Arm of the Forbidden One", 1),
            ("Right Leg of the Forbidden One", 1),
            ("Rude Kaiser", 1),
            ("Silver Fang", 1),
            ("Summoned Skull", 1),
            ("Torike", 1),
            ("Winged Dragon, Guardian of the Fortress [A]", 1),
            ("Zombie Warrior", 1),
            ("Catapult Turtle", 1),
            ("Dark Sage", 1),
            ("Exodia the Forbidden One", 1),
            ("Kuriboh", 1),
            ("Sangan", 1),
            ("Black Luster Soldier", 1),
            ("Magician of Black Chaos", 1),
            ("Black Skull Dragon", 1),
            ("Dragon Master Knight", 1),
            ("Gaia the Dragon Champion", 1),
            ("Black Luster Ritual", 1),
            ("Book of Secret Arts", 1),
            ("Brain Control", 1),
            ("Breath of Light", 1),
            ("Burning Land", 1),
            ("Dark Hole", 1),
            ("Dark Magic Ritual [A]", 1),
            ("De-Spell", 1),
            ("Full Moon [A]", 1),
            ("Horn of the Unicorn", 1),
            ("Living Arrow [A]", 1),
            ("Magical Hats", 1),
            ("Makiu, the Magical Mist", 1),
            ("Monster Reborn", 1),
            ("Monster Recovery", 1),
            ("Monster Replace [A]", 1),
            ("Multiply", 1),
            ("Mystic Box", 1),
            ("Polymerization", 1),
            ("Soul Release", 1),
            ("Swords of Revealing Light", 1),
            ("The Eye of Truth", 1),
            ("Mirror Force", 1),
            ("Spellbinding Circle", 1),
        ],
        "Friendship": [
            ("Anthrosaurus", 1),
            ("Basic Insect", 1),
            ("Claw Reacher", 1),
            ("Cyber Commander", 1),
            ("Dark Magician", 1),
            ("Flame Swordsman", 1),
            ("Happy Lover", 1),
            ("Kagemusha of the Blue Flame", 2),
            ("Kageningen", 1),
            ("Meotoko", 1),
            ("Rock Ogre Grotto #1", 1),
            ("Skull Stalker", 1),
            ("The Furious Sea King", 1),
            ("Magician of Faith", 1),
            ("Breath of Light", 1),
            ("Monster Reborn", 1),
            ("Horn of Heaven", 1),
        ],
        "Battle City": [
            ("Alpha The Magnet Warrior", 1),
            ("Beaver Warrior", 1),
            ("Beta The Magnet Warrior", 1),
            ("Celtic Guardian", 1),
            ("Dark Magician", 1),
            ("Feral Imp", 1),
            ("Gamma The Magnet Warrior", 1),
            ("Gazelle the King of Mythical Beasts", 1),
            ("Giant Soldier of Stone", 2),
            ("Jack's Knight", 1),
            ("Queen's Knight", 1),
            ("Red-Eyes Black Dragon", 1),
            ("Silver Fang", 1),
            ("Summoned Skull", 1),
            ("Beast of Gilfer [A]", 1),
            ("Berfomet", 1),
            ("Big Shield Gardna", 1),
            ("Buster Blader", 1),
            ("Cyber Jar", 1),
            ("Dark Magician Girl", 1),
            ("Electromagnetic Turtle", 1),
            ("King's Knight", 1),
            ("Kuriboh", 1),
            ("Obelisk the Tormentor", 1),
            ("Obnoxious Celtic Guard", 1),
            ("Slifer the Sky Dragon", 1),
            ("The Winged Dragon of Ra", 1),
            ("Valkyrion the Magna Warrior", 1),
            ("Chimera the Flying Mythical Beast", 1),
            ("Dark Paladin", 1),
            ("Brain Control", 1),
            ("Brain Control", 1),
            ("Card Destruction", 1),
            ("Card of Sanctity", 1),
            ("Change of Heart", 1),
            ("Cursebreaker [A]", 1),
            ("De-Fusion", 1),
            ("De-Spell", 1),
            ("Diffusion Wave-Motion", 1),
            ("Double Spell", 1),
            ("Exchange", 1),
            ("Exile of the Wicked", 1),
            ("Fiend's Sanctuary", 1),
            ("Full Moon [A]", 1),
            ("Graceful Charity", 1),
            ("Lightforce Sword", 1),
            ("Magic Formula", 2),
            ("Magical Dimension", 1),
            ("Magical Hats", 1),
            ("Monster Reborn", 1),
            ("Multiply", 1),
            ("Mystic Box", 1),
            ("Necromancy [A]", 1),
            ("Polymerization", 1),
            ("Pot of Greed", 1),
            ("Premature Burial", 1),
            ("Ragnarok [A]", 1),
            ("Soul Taker", 1),
            ("Spell Textbook [A]", 1),
            ("Swords of Revealing Light", 1),
            ("Chain Destruction", 1),
            ("Collected Power", 1),
            ("Chain Destruction", 1),
            ("Collected Power", 1),
            ("Disgraceful Charity [A]", 1),
            ("Dust Tornado", 1),
            ("Life Shaver", 1),
            ("Light of Intervention", 1),
            ("Magic Cylinder", 1),
            ("Magic Jammer", 1),
            ("Magician's Selection [A]", 1),
            ("Mirror Force", 1),
            ("Mystical Refpanel", 1),
            ("Seven Tools of the Bandit", 1),
            ("Shift", 1),
            ("Soul Rope", 1),
        ],
    },
    "Seto Kaiba": {
        "Duelist Kingdom": [
            ("Blue-Eyes White Dragon", 3),
            ("Battle Ox", 2),
        ]
    },
    "Joey Wheeler": {
        "Joey's Warrior Deck": [
            ("Red-Eyes Black Dragon", 2),
            ("Gearfried the Iron Knight", 3),
        ]
    }
}
