#TODO: Finish Yugi, Start Kaiba and Joey

DECKS_DATA = {
    "Yugi Muto": {
        "Toei - First Series": [
            ("Big Tree [A]", 1),
            ("Black Scorpion [A]", 1),
            ("Blackland Fire Dragon", 1),
            ("Chimera [A]", 1),
            ("Dark Mammoth [A]", 1),
            ("Death Wolf [A]", 1),
            ("Ghost [A]", 1),
            ("Iron Beetle [A]", 1),
            ("King Rex [A]", 1),
            ("Koumori Dragon", 1),
            ("Mushroom Man", 1),
            ("Mystical Elf", 1),
            ("Neon Knight [A]", 1),
            ("Night Soldier [A]", 1),
            ("Rock-Gun [A]", 1),
            ("Shadowman [A]", 1),
            ("Skull Servant", 1),
            ("Sleeping Worm [A]", 1),
            ("Summoned Skull", 1),
            ("Violet Hecate [A]", 1),
            ("Clock Card [A]", 1),
            ("Magical Hats", 1),
            ("Flute of Light [A]", 1),
            ("Miraculous Water [A]", 1),
            ("Monster Reborn", 1),
        ],
        "Toei - Death-T": [
            ("Chimera [A]", 1),
            ("Exodia the Forbidden One", 1),
            ("Gaia The Fierce Knight", 1),
            ("Gremlin [A]", 1),
            ("Koumori Dragon", 1),
            ("Left Arm of the Forbidden One", 1),
            ("Left Leg of the Forbidden One", 1),
            ("Mammoth Graveyard", 1),
            ("Right Arm of the Forbidden One", 1),
            ("Right Leg of the Forbidden One", 1),
            ("Winged Dragon, Guardian of the Fortress #1", 1),
            ("Swords of Revealing Light", 1),
        ],
        "Toei - Movie": [
            ("Beaver Warrior", 1),
            ("Celtic Guardian", 1),
            ("Curse of Dragon", 1),
            ("Dark Magician", 1),
            ("Feral Imp", 1),
            ("Gaia The Fierce Knight", 1),
            ("Hitotsu-Me Giant", 1),
            ("Meteor B. Dragon [A]", 1),
            ("Meteor Dragon (Toei) [B]", 1),
            ("Red-Eyes B. Dragon [B]", 1),
            ("Summoned Skull", 1),
            ("Dragonic Pulse of the Land [A]", 1),
            ("Magical Hats", 1),
            ("Polymerization", 1),
            ("Curse of Dark Cross Star [A]", 1),
        ],
        "Duelist Kingdom": [
            ("Battle Steer", 1),
            ("Beaver Warrior", 1),
            ("Celtic Guardian", 1),
            ("Curse of Dragon", 1),
            ("Dark Magician", 1),
            ("Feral Imp", 1),
            ("Gaia The Fierce Knight", 1),
            ("Giant Soldier of Stone", 1),
            ("Griffore", 1),
            ("Horn Imp", 1),
            ("Koumori Dragon", 1),
            ("Left Arm of the Forbidden One", 1),
            ("Left Leg of the Forbidden One", 1),
            ("Mammoth Graveyard", 1),
            ("Mystical Elf", 1),
            ("Right Arm of the Forbidden One", 1),
            ("Right Leg of the Forbidden One", 1),
            ("Rude Kaiser", 1),
            ("Silver Fang", 1),
            ("Summoned Skull", 1),
            ("Torike", 1),
            ("Winged Dragon, Guardian of the Fortress [A]", 1),
            ("Zombie Warrior", 1),
            ("Catapult Turtle", 1),
            ("Dark Sage", 1),
            ("Exodia the Forbidden One", 1),
            ("Kuriboh", 1),
            ("Sangan", 1),
            ("Black Luster Soldier", 1),
            ("Magician of Black Chaos", 1),
            ("Black Skull Dragon", 1),
            ("Dragon Master Knight", 1),
            ("Gaia the Dragon Champion", 1),
            ("Black Luster Ritual", 1),
            ("Book of Secret Arts", 1),
            ("Brain Control", 1),
            ("Breath of Light", 1),
            ("Burning Land", 1),
            ("Dark Hole", 1),
            ("Dark Magic Ritual [A]", 1),
            ("De-Spell", 1),
            ("Full Moon [A]", 1),
            ("Horn of the Unicorn", 1),
            ("Living Arrow [A]", 1),
            ("Magical Hats", 1),
            ("Makiu, the Magical Mist", 1),
            ("Monster Reborn", 1),
            ("Monster Recovery", 1),
            ("Monster Replace [A]", 1),
            ("Multiply", 1),
            ("Mystic Box", 1),
            ("Polymerization", 1),
            ("Soul Release", 1),
            ("Swords of Revealing Light", 1),
            ("The Eye of Truth", 1),
            ("Mirror Force", 1),
            ("Spellbinding Circle", 1),
        ]
    },
    "Seto Kaiba": {
        "Duelist Kingdom": [
            ("Blue-Eyes White Dragon", 3),
            ("Battle Ox", 2),
        ]
    },
    "Joey Wheeler": {
        "Joey's Warrior Deck": [
            ("Red-Eyes Black Dragon", 2),
            ("Gearfried the Iron Knight", 3),
        ]
    }
}
