ARC_NAMES = {
    "Toei - First Series",
    "Toei - Death-T",
    "Toei - Movie",
    "Duelist Kingdom",
    "Battle City",
    "Virtual World",
    "Waking the Dragons",
    "Grand Championship",
    "Dawn of the Duel",
    "Pyramid of Light",
    "3D Bonds Beyond Time",
    "The Dark Side of Dimensions",
    "Early Manga",
    "Manga - Duelist Kingdom",
    "Manga - Battle City",
    "Manga - Millennium World",
    "Novel",
    "North American World Championship Qualifier 2011",
    "Championship Series Providence 2012",
    "World Championship 2013",
    "North American World Championship Qualifier 2014",
    "World Championship 2016 Special",
    "V Jump Magazine",
    "World Championship 2019 Special",
    "Live-action Speed Duel 2020",
    "World Championship Qualifier 2024",
    "Duel Monsters",
    "Dark Duel Stories",
    "The Eternal Duelist Soul",
    "The Sacred Cards",
    "World Championship 2004",
    "The Dawn of Destiny",
    "Reshef of Destruction",
    "7 Trials to Glory: Standard",
    "7 Trials to Glory: Advanced",
    "North American World Championship Qualifiers 2012",
    "North American World Championship Qualifiers 2013",
    "Worldwide Edition: Stairway to the Destined Duel",
    "The Falsebound Kingdom - Starter",
    "Reshef of Destruction (2)",
    "World Championship 2007",
    "World Championship 2007 (2)",
    "Online Duel Accelerator",
    "Capsule Monsters",
    "Possessed",
    "North American World Championship Qualifiers 2013 Special",
    "North American World Championship Qualifiers 2015 Special",
    "North American World Championship Qualifiers 2017 Special",
    "YCS Origins 2016 Special"
}