#https://www.yugioh.com/characters
#https://yugioh.fandom.com/wiki/Portal:Yu-Gi-Oh!_anime_characters
#https://yugioh.fandom.com/wiki/Category:Characters%27_Decks
#TODO: Check other duelists decks that are not listed on character pages.
#https://yugioh.fandom.com/wiki/Category:Character_portals
#TODO: Check decks that don't have duelists, like Konami Packs or Archetypes Official ones.
DUELISTS = [
    ("Yugi Muto", "images/duelists/yugi.png"),
    ("Seto Kaiba", "images/duelists/kaiba.png"),
    ("Joey Wheeler", "images/duelists/joey.png"),
    ("Téa Gardner", "images/duelists/tea.png"),
    ("Tristan Taylor", "images/duelists/tristan.png"),
    ("Solomon Muto", "images/duelists/solomon.png"),
    ("Leon von Schroeder", "images/duelists/leon.webp"),
    ("Maximillion Pegasus", "images/duelists/pegasus.png"),
    ("Lumis", "images/duelists/lumis.png"),
    ("Umbra", "images/duelists/umbra.png"),
    ("Dartz", "images/duelists/dartz.png"),
    ("Anubis", "images/duelists/anubis.webp"),
    ("Duke Devlin", "images/duelists/duke.webp"),
    ("Arkana", "images/duelists/arkana.png"),
    # =========================
    # TODO: Below
    # =========================
    ("Yami Yugi", "images/duelists/placeholder.webp"), #TODO - Check what decks are exclusive to him
    ("Mokuba Kaiba", "images/duelists/placeholder.webp"),
    ("Serenity Wheeler", "images/duelists/placeholder.webp"),
    ("Mai Valentine", "images/duelists/placeholder.webp"),
    ("Bakura Ryou", "images/duelists/placeholder.webp"),
    ("Yami Bakura", "images/duelists/placeholder.webp"),
    ("Shadi", "images/duelists/placeholder.webp"),
    ("Rebecca", "images/duelists/placeholder.webp"),
    ("Arthur Hopkins", "images/duelists/placeholder.webp"),
    ("Ishizu Ishtar", "images/duelists/placeholder.webp"),
    ("Weevil", "images/duelists/placeholder.webp"),
    ("Rex Raptor", "images/duelists/placeholder.webp"),
    ("Mako Tsunami", "images/duelists/placeholder.webp"),
    ("Ghost Kaiba", "images/duelists/placeholder.webp"),
    ("PaniK", "images/duelists/placeholder.webp"),
    ("Bandit Keith", "images/duelists/placeholder.webp"),
    ("Bonz", "images/duelists/placeholder.webp"),
    ("Para", "images/duelists/placeholder.webp"),
    ("Dox", "images/duelists/placeholder.webp"),
    ("Marik Ishtar", "images/duelists/placeholder.webp"),
    ("Yami Marik", "images/duelists/placeholder.webp"),
    ("Odion", "images/duelists/placeholder.webp"),
    ("Seeker", "images/duelists/placeholder.webp"),
    ("Strings", "images/duelists/placeholder.webp"),
    ("Noah Kaiba", "images/duelists/placeholder.webp"),
    ("Gozaburo Kaiba", "images/duelists/placeholder.webp"),
    ("Gansley", "images/duelists/placeholder.webp"),
    ("Crump", "images/duelists/placeholder.webp"),
    ("Johnson", "images/duelists/placeholder.webp"),
    ("Nezzbitt", "images/duelists/placeholder.webp"),
    ("Leichter", "images/duelists/placeholder.webp"),
    ("Rafael", "images/duelists/placeholder.webp"),
    ("Valon", "images/duelists/placeholder.webp"),
    ("Alister", "images/duelists/placeholder.webp"),
    ("Gurimo", "images/duelists/placeholder.webp"),
    ("Zigfried von Schroeder", "images/duelists/placeholder.webp"),
    ("Vivian Wong", "images/duelists/placeholder.webp"),
    ("Shimon Muran", "images/duelists/placeholder.webp"),
    ("Kuriboh", "images/duelists/placeholder.webp"),
    ("Red-Eyes B.Dragon", "images/duelists/placeholder.webp"),
    ("Tetsu Trudge", "images/duelists/placeholder.webp"),
    ("Johnny Steps", "images/duelists/placeholder.webp"),
    ("Roland", "images/duelists/placeholder.webp"),
    ("Espa Roba", "images/duelists/placeholder.webp"),
    ("Jean-Claude Magnum", "images/duelists/placeholder.webp"),
    ("Rick", "images/duelists/placeholder.webp"),
    ("KC DuelTek 760", "images/duelists/placeholder.webp"),
]