ui_text = {
    "en": {
        # ========================
        #   LOADING FRAME
        # ========================
        "loading_title": "Initializing Database",
        "loading_cards": "Loading Cards...",
        "loading_tip": "Please wait a few minutes...",
        "loading_error": "Error loading database!",
        # ===============================
        #  CHANGING LANGUAGE DIALOG
        # ===============================
        "changing_language_title": "Changing Language",
        "changing_language": "Changing language, please wait",
        "error": "Error",
        "language_change_failed": "There was an error changing language",
        # ================================
        #   HEADER
        # ================================
        "read_docs": "Card Consistency File",
        "language": "Language",
        # ================================
        #   HOME FRAME
        # ================================
        "home_title": "Welcome to the Yu-Gi-Oh! Desktop Companion App",
        "home_subtitle": "Browse cards, inspect duelists and their decks and build your own.",
        "check_cards": "Check Available Cards",
        "duelists": "View Duelists",
        "custom_decks": "View Custom Decks",
        "cards_total": "Cards Total",
        "duelists_total": "Duelists Total",
        "user_decks_total": "User Decks Total",
        "dataset_version": "Dataset Version",
        "dataset_version_unknown": "Dataset Version: Unknown",
        "last_update": "Last Updated",
        # ================================
        #  CARDS FRAME
        # ================================
        "search_card": "Card Search",
        # ================================
        #  DUELISTS FRAME
        # ================================
        "select_duelist": "Select a Duelist",
        # ================================
        #  DUELISTS DETAILS FRAME
        # ================================
        "complete_deck": "Complete Deck",
        "incomplete_deck": "Incomplete Deck",
        "duelist_decks": "{name} Decks",
        "show_exclusive_cards": "Show exclusive cards",
        "no_decks_found": "No Decks Found",
        "export_deck": "Export Deck",
        "deck_export_success": "Deck(s) Exported Successfully!",
        "deck_export_fail": "Error! Deck Export Failed.",
        "no_decks_exported": "No decks were exported",
        # ================================
        #  CUSTOM DECKS FRAME
        # ================================
        "import_deck": "Import Deck",
        "could_not_read_deck_file": "Error! Could not read deck file",
        "invalid_card_entry": "Error! Invalid Card Format",
        "could_not_import_card": "Error importing card from this deck",
        "deck_imported_successfully": "Deck Imported Successfully!",
        "deck_import_failed": "Error Importing Deck!",
        "deck_name": "Deck Name",
        "total_cards": "Main / Extra Cards",
        "used": "Used",
        "new_deck": "Create New Deck",
        "edit": "Edit Deck",
        "toggle_used": "Toggle Used",
        "delete": "Delete Deck",
        "add_to_deck": "Add to Deck",
        "remove_one": "Remove one Copy",
        "remove_card": "Remove Cards",
        "yes": "Yes",
        "no": "No",
        "editing_deck": "Now Editing",
        "deck_cards": "Deck Cards",
        "enter_deck_name": "Enter Deck Name",
        "enter_imported_deck_name": "Enter Imported Deck Name",
        "delete_deck": "Delete Deck",
        "confirm_delete_deck": "Are you sure you want to delete this deck?",
        "deck_name_already_exists": "There is already a deck with this name.",
        "deck_deleted_successfully": "Deck(s) Deleted successfully!",
        "no_decks_deleted": "No deck to delete",
        "rename_deck": "Rename Deck",
        "no_decks_to_export": "No Selected Deck to Export",
        "deck_not_found": "Deck not found",
        "search_decks": "Search Decks",
        # ================================
        #  UI
        # ================================
        "return": "Return",
        "card_details": "Show Card Details",
        "select_card": "Select a Card",
        "spell_card": "Spell Card",
        "trap_card": "Trap Card",
        "main_deck": "Deck Principal",
        "extra_deck": "Deck Extra",
        "monsters": "Monster Cards",
        "spells": "Spell Cards",
        "traps": "Trap Cards",
        "exclusive_cards": "Exclusive Cards",
        "other_cards": "Other Cards",
        "new_cards_added": "New Cards Added",
        "cards_added": "Card(s) Added",
        "update_available_title": "New Update Available!",
        "update_available_message": "There is a new update available. Do you wish to install it?",
        "no_changelog_available": "No Changelog Available",
        "download_update": "Download Update",
        "open_in_browser": "Open in Browser",
        "download_complete": "Download Complete!",
        "downloading_update": "Downloading Update",
        "update_downloaded": "Update downloaded! The app will now restart",
        "update_fail": "Error Downloading Update",
        "ignore": "Ignore",
        "updater_not_found": "Updater not found",
        # ================================
        #  DUELISTS
        # ================================
        "yugi_muto": "Yugi Muto",
        "seto_kaiba": "Seto Kaiba",
        "joey_wheeler": "Joey Wheeler",
        "tea_gardner": "Téa Gardner",
        "tristan_taylor": "Tristan Taylor",
        "solomon_muto": "Solomon Muto",
        "maximillion_pegasus": "Maximillion Pegasus",
        "lumis": "Lumis",
        "umbra": "Umbra",
        "dartz": "Dartz",
        "anubis": "Anubis",
        "duke_devlin": "Duke Devlin",
        "arkana": "Arkana",
        "weevil_underwood": "Weevil Underwood",
        "mai_valentine": "Mai Valentine",
        "mako_tsunami": "Mako Tsunami",
        "bonz": "Bonz",
        "alister": "Alister",
        "arthur_hopkins": "Arthur Hopkins",
        "rebecca": "Rebecca Hopkins",
        "ishizu_ishtar": "Ishizu Ishtar",
        "duel_computers": "Duel Computers",
        "ventriloquist_of_the_dead": "Ventriloquist of the Dead",
        "serenity_wheeler": "Serenity Wheeler",
        "panik": "PaniK",
        "mokuba_kaiba": "Mokuba Kaiba",
        "dark_magician_girl": "Dark Magician Girl",
        "shimon_muran": "Shimon Muran",
        "yami_yugi": "Yami Yugi",
        "bakura_ryou": "Bakura Ryou",
        "yami_bakura": "Yami Bakura",
        "shadi": "Shadi",
        "rex_raptor": "Rex Raptor",
        "bandit_keith": "Bandit Keith",
        "para": "Para",
        "dox": "Dox",
        "marik_ishtar": "Marik Ishtar",
        "yami_marik": "Yami Marik",
        "odion": "Odion",
        "seeker": "Seeker",
        "strings": "Strings",
        "noah_kaiba": "Noah Kaiba",
        "gozaburo_kaiba": "Gozaburo Kaiba",
        "rafael": "Rafael",
        "valon": "Valon",
        "kuriboh": "Kuriboh",
        "red_eyes_black_dragon": "Red-Eyes Black Dragon",
        "espa_roba": "Espa Roba",
        "big5": "The Big Five",
        "grand_championship_duelists": "KC Grand Prix",
        "other_duelists_duel_monsters": "Other (DM)",
        "lumis_and_umbra": "Lumis and Umbra",
},
    "pt": {
        #================================
        #   LOADING FRAME
        #================================
        "loading_title": "Inicializando Base de Dados",
        "loading_cards": "Carregando Cartas...",
        "loading_tip": "Aguarde alguns instantes...",
        "loading_error": "Erro de carregamento!",
        "loading_translations": "Carregando Traduções...",
        # ===============================
        #   CHANGING LANGUAGE DIALOG
        # ===============================
        "changing_language_title": "Mudando de idioma",
        "changing_language": "Mudando idioma, por favor aguarde",
        "error": "Erro",
        "language_change_failed": "Erro ao trocar de idioma",
        # ================================
        #   HEADER
        # ================================
        "read_docs": "Arquivo de Consistência de Cartas",
        "language": "Idioma",
        # ================================
        #   HOME FRAME
        # ================================
        "home_title": "Bem-vindo(a) ao Companion App de Yu-Gi-Oh! para Desktop",
        "home_subtitle": "Consulte cartas, visualize decks de duelistas e monte seus próprios decks.",
        "check_cards": "Ver Cartas Disponíveis",
        "duelists": "Ver Duelistas",
        "custom_decks": "Ver Decks Personalizados",
        "cards_total": "Total de Cartas",
        "duelists_total": "Total de Duelistas",
        "user_decks_total": "Total de Decks de Usuário",
        "dataset_version": "Versão do Dataset",
        "dataset_version_unknown": "Versão do Dataset: Desconhecida",
        "last_update": "Atualizado em",
        # ================================
        #  CARDS FRAME
        # ================================
        "search_card": "Busca de Cartas",
        # ================================
        #  DUELISTS FRAME
        # ================================
        "select_duelist": "Selecionar Duelista",
        # ================================
        #  DUELISTS DETAILS FRAME
        # ================================
        "complete_deck": "Deck Completo",
        "incomplete_deck": "Deck Incompleto",
        "duelist_decks": "Decks de {name}",
        "show_exclusive_cards": "Mostrar cartas exclusivas",
        "no_decks_found": "Nenhum Deck encontrado",
        "export_deck": "Exportar Deck",
        "deck_export_success": "Deck(s) Exportado(s) com Sucesso!",
        "deck_export_fail": "Erro! Falha ao Exportar Deck",
        "no_decks_exported": "Nenhum deck foi exportado",
        # ================================
        #  CUSTOM DECKS AND CUSTOM DECK EDITOR FRAME
        # ================================
        "import_deck": "Importar Deck",
        "could_not_read_deck_file": "Erro ao ler arquivo de deck",
        "invalid_card_entry": "Erro! Formato de Carta Incorreto",
        "could_not_import_card": "Erro ao importar carta",
        "deck_imported_successfully": "Deck Importado com Sucesso!",
        "deck_import_failed": "Erro ao importar Deck",
        "deck_name": "Nome do Deck",
        "total_cards": "Cartas Principal / Extra",
        "used": "Utilizado",
        "new_deck": "Criar Novo Deck",
        "edit": "Editar Deck",
        "toggle_used": "Marcar/Desmarcar Usado",
        "delete": "Excluir Deck",
        "add_to_deck": "Adicionar ao Deck",
        "remove_one": "Remover uma Cópia",
        "remove_card": "Remover Cartas",
        "yes": "Sim",
        "no": "Não",
        "editing_deck": "Agora editando",
        "deck_cards": "Cartas do Deck",
        "enter_deck_name": "Insira Nome do Deck",
        "enter_imported_deck_name": "Insira Nome do Deck Importado",
        "delete_deck": "Excluir Deck",
        "deck_deleted_successfully": "Deck(s) Excluído(s) com sucesso!",
        "no_decks_deleted": "Nenhum Deck para excluir",
        "confirm_delete_deck": "Tem certeza que deseja excluir este deck?",
        "deck_name_already_exists": "Já existe um deck com esse nome.",
        "rename_deck": "Renomear Deck",
        "no_decks_to_export": "Não há deck selecionado para exportar",
        "deck_not_found": "Deck não encontrado",
        "search_decks": "Procurar Decks",
        # ================================
        #  UI
        # ================================
        "return": "Voltar",
        "select_card": "Escolha uma Carta",
        "card_details": "Mostrar detalhes da carta",
        "spell_card": "Carta Mágica",
        "trap_card": "Carta Armadilha",
        "skill_card": "Carta de Habilidade",
        "main_deck": "Deck Principal",
        "extra_deck": "Deck Extra",
        "monsters": "Cartas Monstros",
        "spells": "Cartas Mágicas",
        "traps": "Cartas Armadilhas",
        "exclusive_cards": "Cartas Exclusivas",
        "other_cards": "Outras Cartas",
        "new_cards_added": "Novas Cartas Adicionadas",
        "cards_added": "Carta(s) Adicionada(s)",
        "update_available_title": "Nova atualização disponivel!",
        "update_available_message": "Há uma nova atualização. Deseja instalar?",
        "no_changelog_available": "Nenhum Registro de Mudanças foi encontrado",
        "download_update": "Baixar Atualização",
        "downloading_update": "Baixando Atualização",
        "ignore": "Ignorar",
        "open_in_browser": "Abrir no Navegador",
        "download_complete": "Download Concluído!",
        "update_downloaded": "Atualização Baixada! O programa agora irá agora reiniciar",
        "update_fail": "Erro ao baixar atualização",
        "updater_not_found": "Atualizador não encontrado",
        # ================================
        #  DUELISTS
        # ================================
        "yugi_muto": "Yugi Muto",
        "seto_kaiba": "Seto Kaiba",
        "joey_wheeler": "Joey Wheeler",
        "tea_gardner": "Téa Gardner",
        "tristan_taylor": "Tristan Taylor",
        "solomon_muto": "Solomon Muto",
        "maximillion_pegasus": "Maximillion Pegasus",
        "lumis": "Lumis",
        "umbra": "Umbra",
        "dartz": "Dartz",
        "anubis": "Anúbis",
        "duke_devlin": "Duke Devlin",
        "arkana": "Arkana",
        "weevil_underwood": "Weevil Underwood",
        "mai_valentine": "Mai Valentine",
        "mako_tsunami": "Mako Tsunami",
        "bonz": "Bonz",
        "alister": "Alister",
        "arthur_hopkins": "Arthur Hopkins",
        "rebecca": "Rebecca Hopkins",
        "ishizu_ishtar": "Ishizu Ishtar",
        "duel_computers": "Computadores de Duelo",
        "ventriloquist_of_the_dead": "Ventriloquista dos Mortos",
        "serenity_wheeler": "Serenity Wheeler",
        "panik": "PaniK",
        "mokuba_kaiba": "Mokuba Kaiba",
        "dark_magician_girl": "Pequena Maga Negra",
        "shimon_muran": "Shimon Muran",
        "yami_yugi": "Yami Yugi",
        "bakura_ryou": "Bakura Ryou",
        "yami_bakura": "Yami Bakura",
        "shadi": "Shadi",
        "rex_raptor": "Rex Raptor",
        "bandit_keith": "Bandit Keith",
        "para": "Para",
        "dox": "Dox",
        "marik_ishtar": "Marik Ishtar",
        "yami_marik": "Yami Marik",
        "odion": "Odion",
        "seeker": "Seeker",
        "strings": "Strings",
        "noah_kaiba": "Noah Kaiba",
        "gozaburo_kaiba": "Gozaburo Kaiba",
        "rafael": "Rafael",
        "valon": "Valon",
        "kuriboh": "Kuriboh",
        "red_eyes_black_dragon": "Dragão Negro de Olhos Vermelhos",
        "espa_roba": "Espa Roba",
        "big5": "Os Cinco Grandes",
        "grand_championship_duelists": "Grand Prix KC",
        "other_duelists_duel_monsters": "Outros (MD)",
        "lumis_and_umbra": "Lumis e Umbra",
        # ================================
        #  CARDS DETAILS TRANSLATIONS
        # ================================
        # type + subtype
        "Spell Card": "Carta Mágica",
        "Effect": "Efeito",
        "Trap Card": "Carta Armadilha",
        "Normal": "Normal",
        "Pendulum Effect": "Pêndulo Efeito",
        "Fusion": "Fusão",
        "Flip Effect": "Efeito Virar",
        "Ritual Effect": "Efeito Ritual",
        "Tuner": "Regulador",
        "Link": "Link",
        "Token": "Ficha",
        "Normal Tuner": "Regulador Normal",
        "Synchro Tuner": "Regulador Synchro",
        "Spirit": "Espírito",
        "Pendulum Tuner Effect": "Pêndulo Regulador Efeito",
        "Union Effect": "União",
        "XYZ Pendulum Effect": "XYZ Pêndulo Efeito",
        "Gemini": "Gêmeo",
        "Pendulum Effect Fusion": "Pêndulo Fusão Efeito",
        "Pendulum Normal": "Pêndulo Normal",
        "Pendulum Effect Ritual": "Pêndulo Efeito Ritual",
        "Flip Tuner Effect": "Regulador Efeito Virar",
        "Pendulum Flip Effect": "Pêndulo Efeito Virar",
        "Synchro Pendulum Effect": "Synchro Pêndulo Efeito",
        "Skill Card": "Carta de Habilidade",
        # race
        "Quick-Play": "Jogada Rápida",
        "Fiend": "Demônio",
        "Dragon": "Dragão",
        "Continuous": "Contínua",
        "Zombie": "Zumbi",
        "Beast-Warrior": "Besta Guerreira",
        "Fairy": "Fada",
        "Warrior": "Guerreiro",
        "Rock": "Rocha",
        "Spellcaster": "Mago",
        "Winged Beast": "Besta Alada",
        "Plant": "Planta",
        "Beast": "Besta",
        "Machine": "Máquina",
        "Equip": "Equipamento",
        "Field": "Campo",
        "Fish": "Peixe",
        "Thunder": "Trovão",
        "Pyro": "Fogo",
        "Sea Serpent": "Serpente Marítima",
        "Aqua": "Água",
        "Reptile": "Réptil",
        "Counter": "Contra-Ataque",
        "Psychic": "Psíquico",
        "Insect": "Inseto",
        "Illusion": "Ilusão",
        "Dinosaur": "Dinossauro",
        "Divine-Beast": "Besta Divina",
        "Creator God": "Deus Criador",
        # atrributes
        "DARK": "TREVAS",
        "LIGHT": "LUZ",
        "EARTH": "TERRA",
        "FIRE": "FOGO",
        "WIND": "VENTO",
        "WATER": "ÁGUA",
        "DIVINE": "DIVINO",
    }
}
