ui_text = {
    "en": {
        # ========================
        #   LOADING FRAME
        # ========================
        "loading_title": "Initializing Database",
        "loading_cards": "Loading Cards...",
        "loading_tip": "Please wait a few minutes...",
        "loading_error": "Error loading database!",
        # ===============================
        #  CHANGING LANGUAGE DIALOG
        # ===============================
        "changing_language_title": "Changing Language",
        "changing_language": "Changing language, please wait",
        "error": "Error",
        "language_change_failed": "There was an error changing language",
        # ================================
        #   HEADER
        # ================================
        "read_docs": "Card Consistency File",
        "language": "Language",
        # ================================
        #   HOME FRAME
        # ================================
        "home_title": "Welcome to the Yu-Gi-Oh! Desktop Companion App",
        "home_subtitle": "Browse cards, inspect duelists and their decks and build your own.",
        "check_cards": "Check Available Cards",
        "duelists": "View Duelists",
        "custom_decks": "View Custom Decks",
        "cards_total": "Cards Total",
        "duelists_total": "Duelists Total",
        "user_decks_total": "User Decks Total",
        "dataset_version": "Dataset Version",
        "dataset_version_unknown": "Dataset Version: Unknown",
        "last_update": "Last Updated",
        "show_new_cards": "Show New Cards",
        "no_new_cards_added": "No new cards were added",
        "no_new_cards": "There aren't any new cards available",
        # ================================
        #  CARDS FRAME
        # ================================
        "search_card": "Card Search",
        # ================================
        #  DUELISTS FRAME
        # ================================
        "select_duelist": "Select a Duelist",
        "filter_all": "All Duelists",
        "duel_monsters": "Duel Monsters",
        "gx": "GX",
        "filter_by": "Filter by",
        "search_duelist": "Search duelist",
        # ================================
        #  DUELISTS DETAILS FRAME
        # ================================
        "complete_deck": "Complete Deck",
        "incomplete_deck": "Incomplete Deck",
        "duelist_decks": "{name} Decks",
        "show_exclusive_cards": "Show exclusive cards",
        "no_decks_found": "No Decks Found",
        "export_deck": "Export Deck(s)",
        "deck_exporter": "Deck Exporter",
        "deck_export_success": "Deck Exported Successfully!",
        "decks_export_success": "Decks Exported Successfully!",
        "deck_import_success": "Deck Imported Successfully!",
        "decks_import_success": "Decks Imported Successfully!",
        "deck_export_fail": "Error! Deck Export Failed.",
        "no_decks_exported": "No decks were exported",
        "generate_deck": "Generate Deck",
        "not_enough_cards": "Not enough cards to generate a deck.",
        "deck_generator": "Deck Generator",
        "generated_deck": "Generated Deck",
        "generate_another_deck": "Generate Another Deck",
        "text_view": "Text",
        "gallery_view": "Gallery",
        "loading": "Loading...",
        "deck": "Deck",
        "export_individual_deck": "Export Deck",
        # ================================
        #  CUSTOM DECKS FRAME
        # ================================
        "import_deck": "Import Deck(s)",
        "deck_importer": "Deck Importer",
        "could_not_read_deck_file": "Error! Could not read deck file",
        "invalid_card_entry": "Error! Invalid Card Format",
        "could_not_import_card": "Error importing card from this deck",
        "deck_imported_successfully": "Deck Imported Successfully!",
        "deck_import_failed": "Error Importing Deck!",
        "deck_name": "Deck Name",
        "total_cards": "Main / Extra Deck",
        "used": "Used",
        "new_deck": "Create New Deck",
        "edit": "Edit Deck",
        "toggle_used": "Toggle Used",
        "delete": "Delete Deck",
        "add_to_deck": "Add to Deck",
        "remove_one": "Remove one Copy",
        "remove_card": "Remove Cards",
        "yes": "Yes",
        "no": "No",
        "editing_deck": "Now Editing",
        "deck_cards": "Deck Cards",
        "enter_deck_name": "Enter Deck Name",
        "enter_imported_deck_name": "Enter Imported Deck Name",
        "delete_deck": "Delete Deck(s)",
        "deck_remover": "Deck Remover",
        "confirm_delete_deck": "Are you sure you want to delete this deck?",
        "confirm_delete_decks": "Are you sure you want to delete these decks?",
        "deck_name_already_exists": "There is already a deck with this name.",
        "deck_deleted_successfully": "Deck(s) Deleted successfully!",
        "no_decks_deleted": "No deck to delete",
        "rename_deck": "Rename Deck",
        "no_decks_to_export": "Please select a deck to export",
        "deck_not_found": "Deck not found",
        "search_decks": "Search Decks",
        "invalid_deck_file": "Invalid Deck File",
        "limit_reached": "Limit reached",
        "card_limit_reached": "Unable to add more cards. Limit of 3 reached.",
        # ================================
        #  UI
        # ================================
        "return": "Return",
        "card_details": "Show Card Details",
        "select_card": "Select a Card",
        "spell_card": "Spell Card",
        "trap_card": "Trap Card",
        "main_deck": "Main Deck",
        "extra_deck": "Extra Deck",
        "monsters": "Monster Cards",
        "spells": "Spell Cards",
        "traps": "Trap Cards",
        "exclusive_cards": "Exclusive Cards",
        "other_cards": "Other Cards",
        "new_cards_added": "New Cards Added",
        "cards_added": "Card(s) Added",
        "update_available_title": "New Update Available!",
        "update_available_message": "There is a new update available. Do you wish to install it?",
        "no_changelog_available": "No Changelog Available",
        "download_update": "Download Update",
        "open_in_browser": "Open in Browser",
        "download_complete": "Download Complete!",
        "downloading_update": "Downloading Update",
        "update_downloaded": "Update downloaded! The app will now restart",
        "update_fail": "Error Downloading Update",
        "ignore": "Ignore",
        "updater_not_found": "Updater not found",
        "cards": "cards",
        "loading_database": "Loading Database",
        "search_for_card": "Search for card",
        "normal_monsters": "NormaL Monsters",
        "effect_monsters": "Effect Monsters",
        "pendulum_monsters": "Pendulum Monsters",
        "ritual_monsters": "Ritual Monsters",
        "fusion_monsters": "Fusion Monsters",
        "fusion_pendulum_monsters": "Pendulum Fusion Monsters",
        "synchro_monsters": "Synchro Monsters",
        "synchro_pendulum_monsters": "Pendulum Synchro Monsters",
        "xyz_monsters": "XYZ Monsters",
        "xyz_pendulum_monsters": "Pendulum XYZ Monsters",
        "link_monsters": "LINK Monsters",
        # ================================
        #  DUELISTS - DUEL MONSTERS
        # ================================
        "yugi_muto": "Yugi Muto",
        "seto_kaiba": "Seto Kaiba",
        "joey_wheeler": "Joey Wheeler",
        "tea_gardner": "Téa Gardner",
        "tristan_taylor": "Tristan Taylor",
        "solomon_muto": "Solomon Muto",
        "maximillion_pegasus": "Maximillion Pegasus",
        "lumis": "Lumis",
        "umbra": "Umbra",
        "dartz": "Dartz",
        "anubis": "Anubis",
        "duke_devlin": "Duke Devlin",
        "arkana": "Arkana",
        "weevil_underwood": "Weevil Underwood",
        "mai_valentine": "Mai Valentine",
        "mako_tsunami": "Mako Tsunami",
        "bonz": "Bonz",
        "alister": "Alister",
        "arthur_hopkins": "Arthur Hopkins",
        "rebecca": "Rebecca Hopkins",
        "ishizu_ishtar": "Ishizu Ishtar",
        "duel_computers": "Duel Computers",
        "ventriloquist_of_the_dead": "Ventriloquist of the Dead",
        "serenity_wheeler": "Serenity Wheeler",
        "panik": "PaniK",
        "mokuba_kaiba": "Mokuba Kaiba",
        "dark_magician_girl": "Dark Magician Girl",
        "shimon_muran": "Shimon Muran",
        "yami_yugi": "Yami Yugi",
        "bakura_ryou": "Bakura Ryou",
        "yami_bakura": "Yami Bakura",
        "shadi": "Shadi",
        "rex_raptor": "Rex Raptor",
        "bandit_keith": "Bandit Keith",
        "para": "Para",
        "dox": "Dox",
        "marik_ishtar": "Marik Ishtar",
        "yami_marik": "Yami Marik",
        "odion": "Odion",
        "seeker": "Seeker",
        "strings": "Strings",
        "noah_kaiba": "Noah Kaiba",
        "gozaburo_kaiba": "Gozaburo Kaiba",
        "rafael": "Rafael",
        "valon": "Valon",
        "kuriboh": "Kuriboh",
        "red_eyes_black_dragon": "Red-Eyes Black Dragon",
        "espa_roba": "Espa Roba",
        "big5": "The Big Five",
        "grand_championship_duelists": "KC Grand Prix",
        "other_duelists_duel_monsters": "Other (Duel Monsters)",
        "lumis_and_umbra": "Lumis and Umbra",
        "paradox_brothers": "Paradox Brothers",
        "nitemare": "DarkNite/Nitemare",
        # ================================
        #  DUELISTS - GX
        # ================================
        "jean_louis_bonaparte": "Jean-Louis Bonaparte",
        "slade_princeton": "Slade Princeton",
        "jaden_yuki": "Jaden Yuki",
        "syrus_truesdale": "Syrus Truesdale",
        "alexis_rhodes": "Alexis Rhodes",
        "chazz_princeton": "Chazz Princeton",
        "bastion_misawa": "Bastion Misawa",
        "zane_truesdale": "Zane Truesdale",
        "vellian_crowler": "Vellian Crowler",
        "blair_flannigan": "Blair Flannigan",
        "lyman_banner": "Lyman Banner",
        "pharaoh": "Pharaoh",
        "sheppard": "Sheppard",
        "chumley_huffington": "Chumley Huffington",
        "aster_phoenix": "Aster Phoenix",
        "tyranno_hassleberry": "Tyranno Hassleberry",
        "shirley": "Shirley",
        "echo": "Echo",
        "jesse_anderson": "Jesse Anderson",
        "axel_brodie": "Axel Brodie",
        "jim_crocodile_cook": "Jim Crocodile Cook",
        "adrian_gecko": "Adrian Gecko",
        "kagemaru": "Kagemaru",
        "camula": "Camula",
        "tania": "Tania",
        "don_zaloog": "Don Zaloog",
        "titan": "Titan",
        "abidos_the_third": "Abidos the Third",
        "amnael": "Amnael",
        "atticus_rhodes": "Atticus Rhodes",
        "sartorius": "Sartorius",
        "alien_of_light": "Alien of Light",
        "lorenzo": "Lorenzo",
        "howard_x_miller": "Howard X. Miller",
        "rose": "Rose",
        "sarina": "Sarina",
        "frost": "Frost",
        "thunder": "Thunder",
        "t_bone": "T-Bone",
        "blaze": "Blaze",
        "bob_banter": "Bob Banter",
        "prince_ojin": "Prince Ojin",
        "yubel": "Yubel",
        "thelonious_viper": "Thelonious Viper",
        "stein": "Stein",
        "trapper": "Trapper",
        "marcel_bonaparte": "Marcel Bonaparte",
        "anger_mask": "Anger Mask",
        "laughter_mask": "Laughter Mask",
        "emotionless_mask": "Emotionless Mask",
        "the_supreme_king": "The Supreme King",
        "skull_bishop": "Skull Bishop",
        "chaos_sorcerer": "Chaos Sorcerer",
        "guardian_baou": "Guardian Baou",
        "skilled_dark_magician": "Skilled Dark Magician",
        "skilled_white_magician": "Skilled White Magician",
        "scarr_scout_of_dark_world": "Scarr, Scout of Dark World",
        "zure_knight_of_dark_world": "Zure, Knight of Dark World",
        "kozaky": "Kozaky",
        "bron_mad_king_of_dark_world": "Bron, Mad King of Dark World",
        "trueman": "Trueman",
        "yusuke_fujiwara": "Yusuke Fujiwara",
        "nightshroud": "Nightshroud",
        "fonda_fontaine": "Fonda Fontaine",
        "mindy": "Mindy",
        "jasmine": "Jasmine",
        "sartyr": "Sartyr",
        "sadie": "Sadie",
        "taiyou_torimaki": "Taiyou Torimaki",
        "raizou_mototani": "Raizou Mototani",
        "torrey": "Torrey",
        "harrington_rosewood": "Harrington Rosewood",
        "brier": "Brier",
        "beauregard": "Beauregard",
        "dimitri": "Dimitri",
        "america_uchimura": "America Uchimura",
        "ishiki_erishi": "Ishiki Erishi",
        "belowski": "Belowski",
        "gerard": "Gerard",
        "reginald_van_howel": "Reginald Van Howel",
        "missy": "Missy",
        "winged_kuriboh": "Winged Kuriboh",
        "des_koala": "Des Koala",
        "ojama_trio": "Ojama Trio",
        "sacred_beasts": "Sacred Beasts",
        "neo_spacians": "Neo-Spacians",
        "neo_spacian_aqua_dolphin": "Neo-Spacian Aqua Dolphin",
        "neo_spacian_air_hummingbird": "Neo-Spacian Air Hummingbird",
        "neo_spacian_grand_mole": "Neo-Spacian Grand Mole",
        "des_frog": "Des Frog",
        "neo_spacian_dark_panther": "Neo-Spacian Dark Panther",
        "the_grim_reaper": "The Grim Reaper",
        "the_winged_dragon_of_ra": "The Winged Dragon of Ra",
        "destiny_hero_plasma": "Destiny HERO - Plasma",
        "elemental_hero_neos": "Elemental HERO Neos",
        "crystal_beasts": "Crystal Beasts",
        "crystal_beast_sapphire_pegasus": "Crystal Beast Sapphire Pegasus",
        "jerry_beans_man": "Jerry Beans Man",
        "harpie_lady": "Harpie Lady",
        "titan_the_rock_spirit": "Titan the Rock Spirit",
        "rainbow_dragon": "Rainbow Dragon",
        "advanced_crystal_beasts": "Advanced Crystal Beasts",
        "elemental_hero_flame_wingman": "Elemental HERO Flame Wingman",
        "sky_scout": "Sky Scout",
        "rahz": "Rahz",
        "goblin_elite_attack_force": "Goblin Elite Attack Force",
        "doom_dozer": "Doom Dozer",
        "guardian_of_the_labyrinth": "Guardian of the Labyrinth",
        "claret": "Claret",
        "maiden_of_the_aqua": "Maiden of the Aqua",
        "dancing_fairy": "Dancing Fairy",
        "witty_phantom": "Witty Phantom",
        "exodia_the_forbidden_one": "Exodia the Forbidden One",
        "king": "King",
        "honest": "Honest",
        "kabukid": "Kabukid",
        "franz": "Franz",
        "gelgo": "Gelgo",
        "mathmatica": "Mathmatica",
        "maitre_d": "Maitre D",
        "gorisuke": "Gorisuke",
        "mr_huffington": "Mr. Huffington",
        "jagger_princeton": "Jagger Princeton",
        "wheeler": "Wheeler",
        "czar": "Czar",
        "foster": "Foster",
        "admiral": "Admiral",
        "pierre_the_gambler": "Pierre the Gambler",
        "mr_phoenix": "Mr. Phoenix",
        "mr_shroud": "Mr. Shroud",
        "mad_dog": "Mad Dog",
        "alice": "Alice",
        "linda": "Linda",
        "eisenstein": "Eisenstein",
        "lucien_grimley": "Lucien Grimley",
        "the_d": "The D",
        "doctor_collector": "Doctor Collector",
        "shido_gecko": "Shido Gecko",
        "mr_brodie": "Mr. Brodie",
        "tom": "Tom",
        "osamu": "Osamu",
        "makoto_inotsume": "Makoto Inotsume",
        "daigo_sorano": "Daigo Sorano",
        "tsutomu": "Tsutomu",
},
    "pt": {
        #================================
        #   LOADING FRAME
        #================================
        "loading_title": "Inicializando Base de Dados",
        "loading_cards": "Carregando Cartas...",
        "loading_tip": "Aguarde alguns instantes...",
        "loading_error": "Erro de carregamento!",
        "loading_translations": "Carregando Traduções...",
        # ===============================
        #   CHANGING LANGUAGE DIALOG
        # ===============================
        "changing_language_title": "Mudando de idioma",
        "changing_language": "Mudando idioma, por favor aguarde",
        "error": "Erro",
        "language_change_failed": "Erro ao trocar de idioma",
        # ================================
        #   HEADER
        # ================================
        "read_docs": "Arquivo de Consistência de Cartas",
        "language": "Idioma",
        # ================================
        #   HOME FRAME
        # ================================
        "home_title": "Bem-vindo(a) ao Companion App de Yu-Gi-Oh! para Desktop",
        "home_subtitle": "Consulte cartas, visualize decks de duelistas e monte seus próprios decks.",
        "check_cards": "Ver Cartas Disponíveis",
        "duelists": "Ver Duelistas",
        "custom_decks": "Ver Decks Personalizados",
        "cards_total": "Total de Cartas",
        "duelists_total": "Total de Duelistas",
        "user_decks_total": "Total de Decks de Usuário",
        "dataset_version": "Versão do Dataset",
        "dataset_version_unknown": "Versão do Dataset: Desconhecida",
        "last_update": "Atualizado em",
        "show_new_cards": "Exibir Cartas Novas",
        "no_new_cards_added": "Nenhuma carta nova adicionada",
        "no_new_cards": "Não há cartas novas para exibir",
        # ================================
        #  CARDS FRAME
        # ================================
        "search_card": "Busca de Cartas",
        # ================================
        #  DUELISTS FRAME
        # ================================
        "select_duelist": "Selecionar Duelista",
        "filter_all": "Todos Duelistas",
        "duel_monsters": "Monstros de Duelo",
        "gx": "GX",
        "filter_by": "Filtrar por",
        "search_duelist": "Procurar duelista",
        # ================================
        #  DUELISTS DETAILS FRAME
        # ================================
        "complete_deck": "Deck Completo",
        "incomplete_deck": "Deck Incompleto",
        "duelist_decks": "Decks de {name}",
        "show_exclusive_cards": "Mostrar cartas exclusivas",
        "no_decks_found": "Nenhum Deck encontrado",
        "export_deck": "Exportar Deck(s)",
        "deck_exporter": "Exportador de Deck",
        "deck_export_success": "Deck Exportado com Sucesso!",
        "decks_export_success": "Decks Exportados com Sucesso!",
        "deck_export_fail": "Erro! Falha ao Exportar Deck",
        "deck_import_success": "Deck Importado com Sucesso!",
        "decks_import_success": "Decks Importados com Sucesso!",
        "no_decks_exported": "Nenhum deck foi exportado",
        "generate_deck": "Gerar Deck",
        "not_enough_cards": "Não há cartas suficientes para gerar um deck",
        "deck_generator": "Gerador de Deck",
        "generated_deck": "Deck Gerado",
        "generate_another_deck": "Gerar Outro Deck",
        "text_view": "Texto",
        "gallery_view": "Galeria",
        "loading": "Carregando...",
        "deck": "Deck",
        "export_individual_deck": "Exportar Deck",
        # ================================
        #  CUSTOM DECKS AND CUSTOM DECK EDITOR FRAME
        # ================================
        "import_deck": "Importar Deck(s)",
        "deck_importer": "Importador de Deck",
        "could_not_read_deck_file": "Erro ao ler arquivo de deck",
        "invalid_card_entry": "Erro! Formato de Carta Incorreto",
        "could_not_import_card": "Erro ao importar carta",
        "deck_imported_successfully": "Deck Importado com Sucesso!",
        "deck_import_failed": "Erro ao importar Deck",
        "deck_name": "Nome do Deck",
        "total_cards": "Deck Principal / Extra",
        "used": "Utilizado",
        "new_deck": "Criar Novo Deck",
        "edit": "Editar Deck",
        "toggle_used": "Marcar/Desmarcar Usado",
        "delete": "Excluir Deck",
        "add_to_deck": "Adicionar ao Deck",
        "remove_one": "Remover uma Cópia",
        "remove_card": "Remover Cartas",
        "yes": "Sim",
        "no": "Não",
        "editing_deck": "Agora editando",
        "deck_cards": "Cartas do Deck",
        "enter_deck_name": "Insira Nome do Deck",
        "enter_imported_deck_name": "Insira Nome do Deck Importado",
        "delete_deck": "Excluir Deck(s)",
        "deck_remover": "Removedor de Deck",
        "deck_deleted_successfully": "Deck(s) Excluído(s) com sucesso!",
        "no_decks_deleted": "Nenhum Deck para excluir",
        "confirm_delete_deck": "Tem certeza que deseja excluir este deck?",
        "confirm_delete_decks": "Tem certeza que deseja excluir estes decks?",
        "deck_name_already_exists": "Já existe um deck com esse nome.",
        "rename_deck": "Renomear Deck",
        "no_decks_to_export": "Selecione um deck para exportar",
        "deck_not_found": "Deck não encontrado",
        "search_decks": "Procurar Decks",
        "invalid_deck_file": "Arquivo de deck inválido",
        "limit_reached": "Limite alcançado",
        "card_limit_reached": "Não é possível adicionar mais cartas. Limite de 3 alcançado.",
        # ================================
        #  UI
        # ================================
        "return": "Voltar",
        "select_card": "Escolha uma Carta",
        "card_details": "Mostrar detalhes da carta",
        "spell_card": "Carta Mágica",
        "trap_card": "Carta Armadilha",
        "skill_card": "Carta de Habilidade",
        "main_deck": "Deck Principal",
        "extra_deck": "Deck Extra",
        "monsters": "Cartas Monstro",
        "spells": "Cartas Mágicas",
        "traps": "Cartas Armadilhas",
        "exclusive_cards": "Cartas Exclusivas",
        "other_cards": "Outras Cartas",
        "new_cards_added": "Novas Cartas Adicionadas",
        "cards_added": "Carta(s) Adicionada(s)",
        "update_available_title": "Nova atualização disponivel!",
        "update_available_message": "Há uma nova atualização. Deseja instalar?",
        "no_changelog_available": "Nenhum Registro de Mudanças foi encontrado",
        "download_update": "Baixar Atualização",
        "downloading_update": "Baixando Atualização",
        "ignore": "Ignorar",
        "open_in_browser": "Abrir no Navegador",
        "download_complete": "Download Concluído!",
        "update_downloaded": "Atualização Baixada! O programa agora irá agora reiniciar",
        "update_fail": "Erro ao baixar atualização",
        "updater_not_found": "Atualizador não encontrado",
        "cards": "cartas",
        "loading_database": "Carregando banco de dados",
        "search_for_card": "Procurar carta",
        "normal_monsters": "Monstros Normais",
        "effect_monsters": "Monstros de Efeito",
        "pendulum_monsters": "Monstros Pêndulo",
        "ritual_monsters": "Monstros Ritual",
        "fusion_monsters": "Monstros Fusão",
        "fusion_pendulum_monsters": "Monstros Fusão Pêndulo",
        "synchro_monsters": "Monstros Sincro",
        "synchro_pendulum_monsters": "Monstros Sincro Pêndulo",
        "xyz_monsters": "Monstros XYZ",
        "xyz_pendulum_monsters": "Monstros XYZ Pêndulo",
        "link_monsters": "Monstros LINK",
        # ================================
        #  DUELISTS - DUEL MONSTERS
        # ================================
        "yugi_muto": "Yugi Muto",
        "seto_kaiba": "Seto Kaiba",
        "joey_wheeler": "Joey Wheeler",
        "tea_gardner": "Téa Gardner",
        "tristan_taylor": "Tristan Taylor",
        "solomon_muto": "Solomon Muto",
        "maximillion_pegasus": "Maximillion Pegasus",
        "lumis": "Lumis",
        "umbra": "Umbra",
        "dartz": "Dartz",
        "anubis": "Anúbis",
        "duke_devlin": "Duke Devlin",
        "arkana": "Arkana",
        "weevil_underwood": "Weevil Underwood",
        "mai_valentine": "Mai Valentine",
        "mako_tsunami": "Mako Tsunami",
        "bonz": "Bonz",
        "alister": "Alister",
        "arthur_hopkins": "Arthur Hopkins",
        "rebecca": "Rebecca Hopkins",
        "ishizu_ishtar": "Ishizu Ishtar",
        "duel_computers": "Computadores de Duelo",
        "ventriloquist_of_the_dead": "Ventriloquista dos Mortos",
        "serenity_wheeler": "Serenity Wheeler",
        "panik": "PaniK",
        "mokuba_kaiba": "Mokuba Kaiba",
        "dark_magician_girl": "Pequena Maga Negra",
        "shimon_muran": "Shimon Muran",
        "yami_yugi": "Yami Yugi",
        "bakura_ryou": "Bakura Ryou",
        "yami_bakura": "Yami Bakura",
        "shadi": "Shadi",
        "rex_raptor": "Rex Raptor",
        "bandit_keith": "Bandit Keith",
        "para": "Para",
        "dox": "Dox",
        "marik_ishtar": "Marik Ishtar",
        "yami_marik": "Yami Marik",
        "odion": "Odion",
        "seeker": "Seeker",
        "strings": "Strings",
        "noah_kaiba": "Noah Kaiba",
        "gozaburo_kaiba": "Gozaburo Kaiba",
        "rafael": "Rafael",
        "valon": "Valon",
        "kuriboh": "Kuriboh",
        "red_eyes_black_dragon": "Dragão Negro de Olhos Vermelhos",
        "espa_roba": "Espa Roba",
        "big5": "Os Cinco Grandes",
        "grand_championship_duelists": "Grand Prix KC",
        "other_duelists_duel_monsters": "Outros (Monstros de Duelo)",
        "lumis_and_umbra": "Lumis e Umbra",
        "paradox_brothers": "Irmãos Paradox",
        "nitemare": "DarkNite/Nitemare",
        # ================================
        #  DUELISTS - GX
        # ================================
        "jean_louis_bonaparte": "Jean-Louis Bonaparte",
        "slade_princeton": "Slade Princeton",
        "jaden_yuki": "Jaden Yuki",
        "syrus_truesdale": "Syrus Truesdale",
        "alexis_rhodes": "Alexis Rhodes",
        "chazz_princeton": "Chazz Princeton",
        "bastion_misawa": "Bastion Misawa",
        "zane_truesdale": "Zane Truesdale",
        "vellian_crowler": "Vellian Crowler",
        "blair_flannigan": "Blair Flannigan",
        "lyman_banner": "Lyman Banner",
        "pharaoh": "Pharaoh",
        "sheppard": "Sheppard",
        "chumley_huffington": "Chumley Huffington",
        "aster_phoenix": "Aster Phoenix",
        "tyranno_hassleberry": "Tyranno Hassleberry",
        "shirley": "Shirley",
        "echo": "Echo",
        "jesse_anderson": "Jesse Anderson",
        "axel_brodie": "Axel Brodie",
        "jim_crocodile_cook": "Jim Crocodile Cook",
        "adrian_gecko": "Adrian Gecko",
        "kagemaru": "Kagemaru",
        "camula": "Camula",
        "tania": "Tania",
        "don_zaloog": "Don Zaloog",
        "titan": "Titan",
        "abidos_the_third": "Abidos the Third",
        "amnael": "Amnael",
        "atticus_rhodes": "Atticus Rhodes",
        "sartorius": "Sartorius",
        "alien_of_light": "Alien of Light",
        "lorenzo": "Lorenzo",
        "howard_x_miller": "Howard X. Miller",
        "rose": "Rose",
        "sarina": "Sarina",
        "frost": "Frost",
        "thunder": "Thunder",
        "t_bone": "T-Bone",
        "blaze": "Blaze",
        "bob_banter": "Bob Banter",
        "prince_ojin": "Prince Ojin",
        "yubel": "Yubel",
        "thelonious_viper": "Thelonious Viper",
        "stein": "Stein",
        "trapper": "Trapper",
        "marcel_bonaparte": "Marcel Bonaparte",
        "anger_mask": "Anger Mask",
        "laughter_mask": "Laughter Mask",
        "emotionless_mask": "Emotionless Mask",
        "the_supreme_king": "The Supreme King",
        "skull_bishop": "Skull Bishop",
        "chaos_sorcerer": "Chaos Sorcerer",
        "guardian_baou": "Guardian Baou",
        "skilled_dark_magician": "Skilled Dark Magician",
        "skilled_white_magician": "Skilled White Magician",
        "scarr_scout_of_dark_world": "Scarr, Scout of Dark World",
        "zure_knight_of_dark_world": "Zure, Knight of Dark World",
        "kozaky": "Kozaky",
        "bron_mad_king_of_dark_world": "Bron, Mad King of Dark World",
        "trueman": "Trueman",
        "yusuke_fujiwara": "Yusuke Fujiwara",
        "nightshroud": "Nightshroud",
        "fonda_fontaine": "Fonda Fontaine",
        "mindy": "Mindy",
        "jasmine": "Jasmine",
        "sartyr": "Sartyr",
        "sadie": "Sadie",
        "taiyou_torimaki": "Taiyou Torimaki",
        "raizou_mototani": "Raizou Mototani",
        "torrey": "Torrey",
        "harrington_rosewood": "Harrington Rosewood",
        "brier": "Brier",
        "beauregard": "Beauregard",
        "dimitri": "Dimitri",
        "america_uchimura": "America Uchimura",
        "ishiki_erishi": "Ishiki Erishi",
        "belowski": "Belowski",
        "gerard": "Gerard",
        "reginald_van_howel": "Reginald Van Howel",
        "missy": "Missy",
        "winged_kuriboh": "Winged Kuriboh",
        "des_koala": "Des Koala",
        "ojama_trio": "Ojama Trio",
        "sacred_beasts": "Sacred Beasts",
        "neo_spacians": "Neo-Spacians",
        "neo_spacian_aqua_dolphin": "Neo-Spacian Aqua Dolphin",
        "neo_spacian_air_hummingbird": "Neo-Spacian Air Hummingbird",
        "neo_spacian_grand_mole": "Neo-Spacian Grand Mole",
        "des_frog": "Des Frog",
        "neo_spacian_dark_panther": "Neo-Spacian Dark Panther",
        "the_grim_reaper": "The Grim Reaper",
        "the_winged_dragon_of_ra": "The Winged Dragon of Ra",
        "destiny_hero_plasma": "Destiny HERO - Plasma",
        "elemental_hero_neos": "Elemental HERO Neos",
        "crystal_beasts": "Crystal Beasts",
        "crystal_beast_sapphire_pegasus": "Crystal Beast Sapphire Pegasus",
        "jerry_beans_man": "Jerry Beans Man",
        "harpie_lady": "Harpie Lady",
        "titan_the_rock_spirit": "Titan the Rock Spirit",
        "rainbow_dragon": "Rainbow Dragon",
        "advanced_crystal_beasts": "Advanced Crystal Beasts",
        "elemental_hero_flame_wingman": "Elemental HERO Flame Wingman",
        "sky_scout": "Sky Scout",
        "rahz": "Rahz",
        "goblin_elite_attack_force": "Goblin Elite Attack Force",
        "doom_dozer": "Doom Dozer",
        "guardian_of_the_labyrinth": "Guardian of the Labyrinth",
        "claret": "Claret",
        "maiden_of_the_aqua": "Maiden of the Aqua",
        "dancing_fairy": "Dancing Fairy",
        "witty_phantom": "Witty Phantom",
        "exodia_the_forbidden_one": "Exodia the Forbidden One",
        "king": "King",
        "honest": "Honest",
        "kabukid": "Kabukid",
        "franz": "Franz",
        "gelgo": "Gelgo",
        "mathmatica": "Mathmatica",
        "maitre_d": "Maitre D",
        "gorisuke": "Gorisuke",
        "mr_huffington": "Mr. Huffington",
        "jagger_princeton": "Jagger Princeton",
        "wheeler": "Wheeler",
        "czar": "Czar",
        "foster": "Foster",
        "admiral": "Admiral",
        "pierre_the_gambler": "Pierre the Gambler",
        "mr_phoenix": "Mr. Phoenix",
        "mr_shroud": "Mr. Shroud",
        "mad_dog": "Mad Dog",
        "alice": "Alice",
        "linda": "Linda",
        "eisenstein": "Eisenstein",
        "lucien_grimley": "Lucien Grimley",
        "the_d": "The D",
        "doctor_collector": "Doctor Collector",
        "shido_gecko": "Shido Gecko",
        "mr_brodie": "Mr. Brodie",
        "tom": "Tom",
        "osamu": "Osamu",
        "makoto_inotsume": "Makoto Inotsume",
        "daigo_sorano": "Daigo Sorano",
        "tsutomu": "Tsutomu",
        # ================================
        #  CARDS DETAILS TRANSLATIONS
        # ================================
        # type + subtype
        "Spell Card": "Carta Mágica",
        "Effect": "Efeito",
        "Trap Card": "Carta Armadilha",
        "Normal": "Normal",
        "Pendulum Effect": "Pêndulo Efeito",
        "Fusion": "Fusão",
        "Flip Effect": "Efeito Virar",
        "Ritual Effect": "Efeito Ritual",
        "Tuner": "Regulador",
        "Link": "Link",
        "Token": "Ficha",
        "Normal Tuner": "Regulador Normal",
        "Synchro Tuner": "Regulador Synchro",
        "Spirit": "Espírito",
        "Pendulum Tuner Effect": "Pêndulo Regulador Efeito",
        "Union Effect": "União",
        "XYZ Pendulum Effect": "XYZ Pêndulo Efeito",
        "Gemini": "Gêmeo",
        "Pendulum Effect Fusion": "Pêndulo Fusão Efeito",
        "Pendulum Normal": "Pêndulo Normal",
        "Pendulum Effect Ritual": "Pêndulo Efeito Ritual",
        "Flip Tuner Effect": "Regulador Efeito Virar",
        "Pendulum Flip Effect": "Pêndulo Efeito Virar",
        "Synchro Pendulum Effect": "Synchro Pêndulo Efeito",
        "Skill Card": "Carta de Habilidade",
        # race
        "Quick-Play": "Jogada Rápida",
        "Fiend": "Demônio",
        "Dragon": "Dragão",
        "Continuous": "Contínua",
        "Zombie": "Zumbi",
        "Beast-Warrior": "Besta Guerreira",
        "Fairy": "Fada",
        "Warrior": "Guerreiro",
        "Rock": "Rocha",
        "Spellcaster": "Mago",
        "Winged Beast": "Besta Alada",
        "Plant": "Planta",
        "Beast": "Besta",
        "Machine": "Máquina",
        "Equip": "Equipamento",
        "Field": "Campo",
        "Fish": "Peixe",
        "Thunder": "Trovão",
        "Pyro": "Fogo",
        "Sea Serpent": "Serpente Marítima",
        "Aqua": "Água",
        "Reptile": "Réptil",
        "Counter": "Contra-Ataque",
        "Psychic": "Psíquico",
        "Insect": "Inseto",
        "Illusion": "Ilusão",
        "Dinosaur": "Dinossauro",
        "Divine-Beast": "Besta Divina",
        "Creator God": "Deus Criador",
        # atrributes
        "DARK": "TREVAS",
        "LIGHT": "LUZ",
        "EARTH": "TERRA",
        "FIRE": "FOGO",
        "WIND": "VENTO",
        "WATER": "ÁGUA",
        "DIVINE": "DIVINO",
    }
}
